### PR TITLE
spar api tweaks

### LINKED ISSUE #700: Accept idp metadata urls on /identity-providers (spar)
### status

approval pending.

### description

Currently, we expect the body to be xml, with the appropriate content-type.  We should also accept content-type `application/json` with this in the body:

```json
{
    "url" : "https://okta.com/51097"
}
```

This should be handled by getting the URL and parsing the body as XML.  In case of success, the URL can be forgotten (should be part of the XML document, too, but we don't use it from this point on).

Estimated effort for backend team: 1 day.

### LINKED ISSUE #703: spar end-points should respond with json body in case of error.
The body of all spar errors should contain the usual error information, like:

```
{
  "code": 0,
  "message": "string",
  "label": "string"
}
```

End-points to check:

- [x] `delete /identity-providers/{id}`
- [x] `get /identity-providers/{id}`
- [x] `get /identity-providers`
- [x] `put /identity-providers`
- [x] `post /identity-providers`
- [x] `delete /scim/auth-tokens`
- [x] `get /scim/auth-tokens`
- [x] `post /scim/auth-tokens`

Other things to check:

- [ ] https://github.com/wireapp/wire-server/blob/87ca01cd318243ab66f6f762358c9be43e283ebc/services/spar/test-integration/Test/Spar/APISpec.hs#L609
- [ ] https://github.com/wireapp/wire-server/blob/87ca01cd318243ab66f6f762358c9be43e283ebc/services/spar/test-integration/Test/Spar/APISpec.hs#L670

Related: #700

### PR DESCRIPTION
**Pull request by fisx**
Tasks:

- [x] ~#703~ (will do this separately)
- [x] Fix #700

### CODE REVIEW

**Comment by fisx** [comment]
Some work on the test suite is still missing, and one test fails because spar has a bug.

This one is my favorite though.  I have no idea what is going on.  At all.

```
  test-integration/Test/LoggingSpec.hs:30:5: 
  1) Logging.logging, loglevel == debug, 400 on finalize-login causes log of entire request
       uncaught exception: IOException of type UserError
       user error (error:140A90A1:lib(20):func(169):reason(161))
```

**Comment by fisx** [comment]
> ```
>   test-integration/Test/LoggingSpec.hs:30:5: 
>   1) Logging.logging, loglevel == debug, 400 on finalize-login causes log of entire request
>        uncaught exception: IOException of type UserError
>        user error (error:140A90A1:lib(20):func(169):reason(161))
> ```

Introduced in cbc4b95.  I think the problem is that when the xml parser fails, the next route is tried.  I need to find out whether servant takes `Content-Type` HTTP headers into account, whether that helps, and most importantly whether there is some other way of steering re-routing (I think there is).

**Comment by neongreen** [comment]
> I need to find out whether servant takes Content-Type HTTP headers into account

It does, though I'm not sure how much it cares about them. When I last looked into it, the answer was "more than most other web frameworks", but I don't remember the details :/

> I think the problem is that when the xml parser fails, the next route is tried.

It will probably work if you replace `ReqBody` with `ReqBody' '[Required, Lenient]`.

**Comment by fisx** [comment]
> > I need to find out whether servant takes Content-Type HTTP headers into account
> 
> It does, though I'm not sure how much it cares about them. When I last looked into it, the answer was "more than most other web frameworks", but I don't remember the details :/
> 
> > I think the problem is that when the xml parser fails, the next route is tried.
> 
> It will probably work if you replace `ReqBody` with `ReqBody' '[Required, Lenient]`.

Thanks, that was useful, and helped me find an even better way to do it.   51d9c49 

The mystical error persists, though.

**Comment by fisx** [comment]
> Some work on the test suite is still missing, and one test fails because spar has a bug.
> 
> This one is my favorite though. I have no idea what is going on. At all.
> 
> ```
>   test-integration/Test/LoggingSpec.hs:30:5: 
>   1) Logging.logging, loglevel == debug, 400 on finalize-login causes log of entire request
>        uncaught exception: IOException of type UserError
>        user error (error:140A90A1:lib(20):func(169):reason(161))
> ```

when i removed the code that made spar talk tls to the idp, this went away.  i still don't want to say i understant it, but it seems like it was just a tls setup issue and can be ignored?

**Pull request merged**
