### PR TITLE
[chore] replace cabal.project.local template and update cabal.project

### PR DESCRIPTION
**Pull request by MangoIV**
## Checklist

 - [x] Add a new entry in an appropriate subdirectory of `changelog.d`
 - [x] Read and follow the [PR guidelines](https://docs.wire.com/developer/developer/pr-guidelines.html)

### CODE REVIEW

**Review by fisx — APPROVED** [review]

**Comment by akshaymankar** [comment]
`package: *` applies to all packages not just local pacakges. I think this would fail if protobuf stuff which is not provided by nix has any warnings.

**Comment by MangoIV** [comment]
can we not overwrite in case we run into warnings for these two packages in future? i.e. 
package * in general and then package proto-lens-protoc ghc-options -Wwarn?

**Comment by MangoIV** [comment]
in fact, I deleted my cabal store and am trying to build right now, it doesn't look as though it's problematic.

**Comment by MangoIV** [comment]
so protolens-protoc compiles without warnings.

**Comment by MangoIV** [comment]
currently proto-lens-protoc and hspec-discover do not emit warnings. I have protected us against them failing in future by adding a -Wwarn flag to them. I think this should resolve the objections.

**Comment by MangoIV** [comment]
There’s even a better option: just don’t use the package stanza at all: https://cabal.readthedocs.io/en/stable/cabal-project-description-file.html#package-configuration-options

**Review by fisx — APPROVED** [review]

**Pull request merged**
