### PR TITLE
Gundeck internal API swagger

### PR DESCRIPTION
**Pull request by pcapriotti**
https://wearezeta.atlassian.net/browse/WPB-11177

`make cr` and direct your browser to http://localhost:8080/api-internal/swagger-ui/gundeck.

page

also 
loc
8-))  (this is before i added golden test stuff to wire-api)

## Checklist

 - [x] Make sure all data types touched here are covered in golden tests
 - [x] To get the correct jsons, run the adjusted golden tests on develop
 - [x] Add a new entry in an appropriate subdirectory of `changelog.d`
 - [x] Read and follow the [PR guidelines](https://docs.wire.com/developer/developer/pr-guidelines.html)
 - [x] Figure out if any config files have to be adjusted because of the new examplePort passed to `internalEndpointsSwaggerDocsAPI`.

### CODE REVIEW

**Comment by fisx** [comment]
in `Presence`:

```
        diff:
        [
            {
                "op": "add",
                "path": "/native_aps/sound",
                "value": null
            }
        ]
```

in `Push`:

```
        diff:
        [
            {
                "op": "add",
                "path": "/native_aps/sound",
                "value": null
            }
        ]
```

**Comment by fisx** [comment]
i paused this.  give it the `ok-to-test` label again if you think concourse is up to it.

**Review by fisx — APPROVED** [review]
I think this can ship, but I'd prefer to have a nod from you @pcapriotti?

**Comment by fisx** [comment]
> i paused this. give it the `ok-to-test` label again if you think concourse is up to it.

unpauseed.

**Comment by fisx** [comment]
i was wrong about the discrepancy with develop (5c76642a0214b71337c37ed7d916227a19ab8633): the explicit null values were on *develop*, not *our branch*, and schema-profunctor omits null values by default.

fixed here: 2b63078275a5ffcf2051e141299dba43026eb2cb

should be ready to be given a last glance now.

**Review by pcapriotti — COMMENTED** [review]
LGTM

**Pull request merged**
