### PR TITLE
[WIP] [blocked: buggy] Cargohold with amazonka (merged version)

### PR DESCRIPTION
**Pull request by neongreen**
This is Tiago's #203 with develop merged into it.

### CODE REVIEW

**Comment by neongreen** [comment]
@tiago-loureiro ❤️

**Comment by tiago-loureiro** [comment]
Current status of this PR:
Most tests fail against real S3 with _Only the last chunk is allowed to have a size less than 8192 bytes_ while there seems to a different issue when running against minio.io: there, it simply times out [as it did beforehand](https://github.com/wireapp/wire-server/pull/203#issuecomment-393028321) ... to be investigated.

**Comment by ChrisPenner** [comment]
AWS tests seem happy now (haven't waited for the long uploads yet though)

non-aws tests still hang on the first attempt to upload; watching minio request logs it seems nothing is happening, but upon killing the integration tests a request immediately goes through with the following error:

```
[REQUEST objectAPIHandlers.PutObjectHandler-fm] [154998117.905572] [2019-02-12 14:19:39 +0000]
PUT /dummy-bucket/v3/persistent/75962a62-eb36-4721-8087-0fc8e2b395ee
Host: 27088b51.ngrok.io
Expect: 100-continue
Content-Md5: 1dD7l/e1ORpJRgcO1UCaqQ==
X-Amz-Decoded-Content-Length: 100000
Content-Type: application/text
X-Amz-Date: 20190212T141935Z
X-Amz-Content-Sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
Authorization: AWS4-HMAC-SHA256 Credential=dummykey/20190212/eu-west-1/s3/aws4_request, SignedHeaders=content-encoding;content-length;content-md5;content-type;expect;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length;x-amz-meta-token;x-amz-meta-user, Signature=46a12098fada66627fd1b8036f7dd0264b334edccb2382ebb54c54db3c9822d7
X-Forwarded-Proto: https
X-Forwarded-For: 62.96.148.44
Accept-Encoding: gzip
X-Amz-Meta-Token: v0uQ1sYa5v6Iv87fWsHyHw==
X-Amz-Meta-User: b55aaa20-dcde-479f-b9d4-16ca5315ac4b
Content-Encoding: aws-chunked

<BODY>

[RESPONSE] [154998117.905572] [2019-02-12 14:19:45 +0000]
403 Forbidden
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 1582A3AB9226FF28
X-Minio-Deployment-Id: 7deecc25-6a3c-481c-a9aa-5c6d8d2458dc
Server: Minio/RELEASE.2019-02-06T21-16-36Z
Accept-Ranges: bytes
Content-Type: application/xml
Vary: Origin
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Resource>/dummy-bucket/v3/persistent/75962a62-eb36-4721-8087-0fc8e2b395ee</Resource><RequestId>1582A3AB9226FF28</RequestId><HostId>3L137</HostId></Error>
```

The failing signature might possibly be a red-herring for an incomplete response body being transmitted, possibly because (conduit maybe) gets stuck part-way through reading a body? I'm uncertain as to why this would be any different for minio than for s3 though.

**Comment by neongreen** [comment]
Added `[WIP]` to the PR name to stop CI from running on it (because CI takes a long time on this one). Once you're done with it, remove the `[WIP]`.

**Comment by jschaul** [comment]
@arianvp discovered https://github.com/axman6/amazonka-s3-streaming which may unblock this PR.

**Comment by fisx** [comment]
this can be closed now, right?

**Pull request closed without merging**
