### PR TITLE
Specialize the error cases on conversation lookup.

### PR DESCRIPTION
**Pull request by fisx**
Fixes https://github.com/wearezeta/backend-issues/issues/870

@tiago-loureiro writes:

> Currently there is no distinction between "there is no conversation with id X" and "you are not a member of the conversation".
> 
> This creates a problem now that we will effectively add "conversation deletion" on the UI and clients need to distinguish between the 2 (i.e., was I kicked or did the conversation get deleted). This is particularly important for new devices or when missing a lot of notifications (note that when deleting conversations clients must delete this locally too but not when getting kicked/leaving conversations).

This PR changes the behavior to return two errors for these two cases:

```haskell
Error status404 "no-conversation" "conversation not found"
Error status403 "access-denied" "Conversation access denied"
```

### CODE REVIEW

**Comment by tiago-loureiro** [comment]
Code change looks good but... no test?

**Comment by fisx** [comment]
> Code change looks good but... no test?

since the integration tests still pass, i presume there wasn't a test for it.  and now there still isn't.  i suppose you want me to change that?  :-)

fine...

**Comment by fisx** [comment]
f4a2cd5 without https://github.com/wireapp/wire-server/pull/841/commits/5e8e06d66ce02c3a13a866a15ccd5a6a9c3e32bc:

```
[...]
      repeat / cancel connect requests:                                FAIL
        Exception: Assertions failed:
         1: 403 =/= 404

        Response was:

        Response {responseStatus = Status {statusCode = 404, statusMessage = "Not Found"}, responseVersion = HTTP/1.1, responseHeaders = [("Transfer-Encoding","chunked"),("Date","Thu, 29 Aug 2019 12:37:30 GMT"),("Server","Warp/3.2.25"),("Content-Type","application/json")], responseBody = Just "{\"code\":404,\"message\":\"conversation no
t found\",\"label\":\"no-conversation\"}", responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}
        CallStack (from HasCallStack):
          error, called at src/Bilge/Assert.hs:69:30 in bilge-0.22.0-8ufUi02ZiYj1pTUQT3VQuV:Bilge.Assert
          <!!, called at src/Bilge/Assert.hs:86:19 in bilge-0.22.0-8ufUi02ZiYj1pTUQT3VQuV:Bilge.Assert
          !!!, called at test/integration/API.hs:762:9 in main:API
      block/unblock a connect/1-1 conversation:                        FAIL
        Exception: Assertions failed:
         1: 403 =/= 404

        Response was:

        Response {responseStatus = Status {statusCode = 404, statusMessage = "Not Found"}, responseVersion = HTTP/1.1, responseHeaders = [("Transfer-Encoding","chunked"),("Date","Thu, 29 Aug 2019 12:37:31 GMT"),("Server","Warp/3.2.25"),("Content-Type","application/json")], responseBody = Just "{\"code\":404,\"message\":\"conversation no
t found\",\"label\":\"no-conversation\"}", responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}
        CallStack (from HasCallStack):
          error, called at src/Bilge/Assert.hs:69:30 in bilge-0.22.0-8ufUi02ZiYj1pTUQT3VQuV:Bilge.Assert
          <!!, called at src/Bilge/Assert.hs:86:19 in bilge-0.22.0-8ufUi02ZiYj1pTUQT3VQuV:Bilge.Assert
          !!!, called at test/integration/API.hs:772:5 in main:API
[...]
      remove members:                                                  FAIL
        Exception: Assertions failed:
         1: 403 =/= 404

        Response was:

        Response {responseStatus = Status {statusCode = 404, statusMessage = "Not Found"}, responseVersion = HTTP/1.1, responseHeaders = [("Transfer-Encoding","chunked"),("Date","Thu, 29 Aug 2019 12:37:39 GMT"),("Server","Warp/3.2.25"),("Content-Type","application/json")], responseBody = Just "{\"code\":404,\"message\":\"conversation not found\",\"label\":\"no-conversation\"}", responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}
        CallStack (from HasCallStack):
          error, called at src/Bilge/Assert.hs:69:30 in bilge-0.22.0-8ufUi02ZiYj1pTUQT3VQuV:Bilge.Assert
          <!!, called at src/Bilge/Assert.hs:86:19 in bilge-0.22.0-8ufUi02ZiYj1pTUQT3VQuV:Bilge.Assert
          !!!, called at test/integration/API.hs:927:5 in main:API
[...]
3 out of 106 tests failed (101.80s)
```

f4a2cd5 with https://github.com/wireapp/wire-server/pull/841/commits/5e8e06d66ce02c3a13a866a15ccd5a6a9c3e32bc:

```
[...]
      repeat / cancel connect requests:                                OK (0.18s)
      block/unblock a connect/1-1 conversation:                        OK (0.14s)
[...]
      remove members:                                                  OK (0.47s)
[...]
All 106 tests passed (96.22s)
```

**Comment by fisx** [comment]
(ok, except for brig...)

**Comment by fisx** [comment]
ready for approv...  erm, review!  :-)

**Pull request merged**
