### PR TITLE
Isovector/brig servant 2022

### PR DESCRIPTION
**Pull request by battermann**
Part of [SQCORE-1166](https://wearezeta.atlassian.net/browse/SQCORE-1166). Ports the Brig UserHandle API to use Servant.

Leaving the last two checkboxes unchecked because I don't know the answer to them.

## Checklist

 - [x] The **PR Title** explains the impact of the change.
 - [x] The **PR description** provides context as to why the change should occur and what the code contributes to that effect. This could also be a link to a JIRA ticket or a Github issue, if there is one.
 - [x] **changelog.d** contains the following bits of information ([details](https://github.com/wireapp/wire-server/blob/develop/docs/developer/changelog.md)):
   - [x] A file with the changelog entry in one or more suitable sub-sections. The sub-sections are marked by directories inside `changelog.d`.

### CODE REVIEW

**Comment by mdimjasevic** [comment]
@isovector , we've been experiencing issues with the CI, which then prevents this PR (and all the other PRs) from getting a green light. We'll retrigger the build in CI as soon as the issues are resolved.

**Comment by isovector** [comment]
CI is green --- someone mind reviewing it? @elland @battermann @mdimjasevic thanks!

**Comment by mdimjasevic** [comment]
> CI is green --- someone mind reviewing it? @elland @battermann @mdimjasevic thanks!

I see that two endpoints listed in https://wearezeta.atlassian.net/browse/SQSERVICES-1642 are not covered by this PR:

- `GET /users/:uid/rich-info`
- `GET /teams/:tid/search`

Should they be part of the PR or should they come in a follow-up PR?

**Comment by isovector** [comment]
@mdimjasevic I'm happy to merge this as is

**Review by mdimjasevic — APPROVED** [review]
Looks good!

**Pull request merged**
