### PR TITLE
Merge pull request #1 from wireapp/develop

### PR DESCRIPTION
**Pull request by FihlaTV**
Laterst-update

### CODE REVIEW

**Comment by FihlaTV** [comment]
updates from aug

**Comment by neongreen** [comment]
@FihlaTV What's going on in this PR? It has no changes and title doesn't clear things up.

**Comment by neongreen** [comment]
Did you do it by mistake?

**Comment by jschaul** [comment]
It appears you meant to make a PR to your fork. (Feel free to open a new PR if you have a non-empty contribution)

**Pull request closed without merging**
