### PR TITLE
[WIP] disentangle types packages

### PR DESCRIPTION
**Pull request by fisx**
Refactoring only, no behavioral changes.

Motivation: https://github.com/wireapp/wire-server/pull/573#issuecomment-455542440

### CODE REVIEW

**Comment by fisx** [comment]
Oh, look: brig-types has been depending on galey-types since early 2017:

```
23418cc56 (Toralf Wittner                2017-04-04 15:10:42 +0200  50)       , galley-types          >= 0.45.7
```

**Comment by fisx** [comment]
based on https://github.com/wireapp/wire-server/pull/577, this should be merged after that.

i'm not sure i like the changes, i think the old code was fine and we should focus on finding the time to merge galley and brig.  but the changes don't make it much worse either.

brig-types still depends on galley-types, which it has since 2017, and after having tried i think it's not worth fixing that.

**Comment by neongreen** [comment]
Is it still WIP?

**Comment by fisx** [comment]
> Is it still WIP?

yes, needs rebase, as is based on #577

**Comment by neongreen** [comment]
@fisx #577 has been merged. I can do the rebase for you and merge this PR if you're fine with that.

**Comment by fisx** [comment]
- resolving merge conflicts would take more time
- this PR does not resolve the issue it was supposed to solve, namely that brig-types depends on galley-types.  this dependency has been around since 2017-04.
- i don't consider the issue very serious, and am behind fixing serious production issues and issues with new features.

i will close this, and we can re-visit the issue when merging brig and galley.

**Comment by neongreen** [comment]
> this PR does not resolve the issue it was supposed to solve

Alright, it's reasonable to close it then.

**Comment by fisx** [comment]
> > this PR does not resolve the issue it was supposed to solve
> 
> Alright, it's reasonable to close it then.

if you can't help yourself and if you feel it's an incremental improvement, e.g. because it removes the cql-flag from brit-types.cabal, i am fine with you merging it.  :-)

**Comment by neongreen** [comment]
I don't care much about this PR to be honest, I just had a mental trigger
for "when XXX is merged, look at XYZ".

I would too prefer to wait until we have time to merge Brig and Galley.

**Pull request closed without merging**
