### PR TITLE
release_2020_04_15

### PR DESCRIPTION
**Pull request by akshaymankar**
# Changelog

## Upgrade steps (IMPORTANT)

1. Update mapping in ElasticSearch (see [./docs/reference/elastic-search.md](./docs/reference/elastic-search.md))
2. Upgrade brig and the other services as usual
3. Migrate data in ElasticSearch (see [./docs/reference/elastic-search.md](./docs/reference/elastic-search.md))

## New features

* Allow `brig-index create` to set ES index settings (#1023)
* Extended team invitations to have name and phone number (#1032)
* Allow team members to be searched by teammates. (#964)
* Better defaults for maxKeyLen and maxValueLen (#1034)

## Bug Fixes

* Fix swagger (#1012, #1031)
* Custom backend lookup by domain is now case-insensitive (#1013)

## Internal Changes

* Federation: resolve opaque IDs at the edges of galley (#1008)
* Qualify all API imports in Galley (#1006)
* types-common: write unit tests for Data.Qualified (#1011)
* Remove subv4 (#1003)
* Add federation feature flag to brig and galley (#1014)
* Add hie.yaml (#1024)
* Improve reproducibility of builds (#1027)
* Update types of some brig endpoints to be federation-aware (#1013)
* Bump to lts-14.27 (#1030)
* Add comments about which endpoints send which events to clients (#1025)
* Minimize dependencies of all brig binaries (#1035)
* Federation: Use status 403 for 'not implemented' (#1036)
* Add endpoint to count team members using ES (#1022)
* Rename brig's userName to userDisplayName to avoid confusion (#1039)
* Upgrade to restund 0.4.14 (#1043)
* Add license headers to all files (#980, #1045)
* Federation: Link related issue IDs (#1041)

### CODE REVIEW

**Comment by akshaymankar** [comment]
@fisx Is there a PR or commit that I could attribute to that bugfix?

**Comment by akshaymankar** [comment]
Wait, that commit did not make the cut. Should I cherry-pick it?

**Comment by tiago-loureiro** [comment]
> Wait, that commit did not make the cut. Should I cherry-pick it?

Only a specific test was added https://github.com/wireapp/wire-server/pull/1051 - the actual fix came as a side-effect of https://github.com/wireapp/wire-server/pull/1013

**Comment by akshaymankar** [comment]
There is nothing new on this branch apart from CHANGELOG, so I will not wait for the tests.

**Pull request merged**
