### PR TITLE
Spar Polysemy: Explicit export lists

### PR DESCRIPTION
**Pull request by isovector**
This PR adds explicit export lists for all the new modules I've introduced when working on Spar.

## Checklist

 - [x] The **PR Title** explains the impact of the change.
 - [x] The **PR description** provides context as to why the change should occur and what the code contributes to that effect. This could also be a link to a JIRA ticket or a Github issue, if there is one.
 - [x] **changelog.d** contains the following bits of information ([details](https://github.com/wireapp/wire-server/blob/develop/docs/developer/changelog.md)):
   - [x] A file with the changelog entry in one or more suitable sub-sections. The sub-sections are marked by directories inside `changelog.d`.

### CODE REVIEW

**Comment by fisx** [comment]
```
 > /wire-server/services/spar/src/Spar/Sem/SAML2.hs:22:5: error:
 >     Ambiguous occurrence ‘meta’
 >     It could refer to
 >        either ‘SAML2.WebSSO.meta’,
 >               imported from ‘SAML2.WebSSO’ at src/Spar/Sem/SAML2.hs:33:1-19
 >               (and originally defined in ‘SAML2.WebSSO.API’)
 >            or ‘Spar.Sem.SAML2.meta’, defined at src/Spar/Sem/SAML2.hs:57:1
 >    |
 > 22 |     meta,
 >    |     ^^^^
 > 
 > /wire-server/services/spar/src/Spar/Sem/SAML2.hs:23:5: error:
 >     Ambiguous occurrence ‘toggleCookie’
 >     It could refer to
 >        either ‘SAML2.WebSSO.toggleCookie’,
 >               imported from ‘SAML2.WebSSO’ at src/Spar/Sem/SAML2.hs:33:1-19
 >               (and originally defined in ‘SAML2.WebSSO.Cookie’)
 >            or ‘Spar.Sem.SAML2.toggleCookie’,
 >               defined at src/Spar/Sem/SAML2.hs:57:1
 >    |
 > 23 |     toggleCookie,
 >    |     ^^^^^^^^^^^^
 > 
 > /wire-server/services/spar/src/Spar/Sem/ScimExternalIdStore.hs:21:5: error:
 >     Ambiguous occurrence ‘lookup’
 >     It could refer to
 >        either ‘Imports.lookup’,
 >               imported from ‘Imports’ at src/Spar/Sem/ScimExternalIdStore.hs:27:1-14
 >               (and originally defined in ‘GHC.List’)
 >            or ‘Spar.Sem.ScimExternalIdStore.lookup’,
 >               defined at src/Spar/Sem/ScimExternalIdStore.hs:39:1
 >    |
 > 21 |     lookup,
 >    |     ^^^^^^
 > 
 > /wire-server/services/spar/src/Spar/Sem/ScimTokenStore.hs:21:5: error:
 >     Ambiguous occurrence ‘lookup’
 >     It could refer to
 >        either ‘Imports.lookup’,
 >               imported from ‘Imports’ at src/Spar/Sem/ScimTokenStore.hs:29:1-14
 >               (and originally defined in ‘GHC.List’)
 >            or ‘Spar.Sem.ScimTokenStore.lookup’,
 >               defined at src/Spar/Sem/ScimTokenStore.hs:40:1
 >    |
 > 21 |     lookup,
 >    |     ^^^^^^
 > 
 > /wire-server/services/spar/src/Spar/Sem/ScimUserTimesStore.hs:21:5: error:
 >     Ambiguous occurrence ‘read’
 >     It could refer to
 >        either ‘Imports.read’,
 >               imported from ‘Imports’ at src/Spar/Sem/ScimUserTimesStore.hs:28:1-14
 >               (and originally defined in ‘Text.Read’)
 >            or ‘Spar.Sem.ScimUserTimesStore.read’,
 >               defined at src/Spar/Sem/ScimUserTimesStore.hs:38:1
 >    |
 > 21 |     read,
 >    |     ^^^^
```

**Comment by isovector** [comment]
@fisx I'm having a hard time getting CI to pass here:

```
2022-01-27T17:34:32Z, D, Connection closed: datacenter1:rack1:127.0.0.1:9042#<socket: 16>
FAIL (91.27s)
        test/integration/API.hs:334:
        Not at least 2 notifications
        Use -p '/Send a push to online and offline users/' to rerun this test only.
      register too many push tokens:                               [gundeck] I, request=N/A, user=22618a7d-1ef5-476b-89e2-ef96ab03390e, token=37565d3d-e349-44, Registering push token
FAIL
        Exception: Assertions failed:
         1: 201 =/= 500
        
        Response was:
        
        Response {responseStatus = Status {statusCode = 500, statusMessage = "Internal Server Error"}, responseVersion = HTTP/1.1, responseHeaders = [("Transfer-Encoding","chunked"),("Date","Thu, 27 Jan 2022 17:35:51 GMT"),("Server","Warp/3.3.17"),("Vary","Accept-Encoding"),("Content-Encoding","gzip"),("Content-Type","application/json")], responseBody = Just "{\"code\":500,\"message\":\"Server Error\",\"label\":\"server-error\"}", responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}
        CallStack (from HasCallStack):
          error, called at src/Bilge/Assert.hs:89:5 in bilge-0.22.0-inplace:Bilge.Assert
          <!!, called at src/Bilge/Assert.hs:107:19 in bilge-0.22.0-inplace:Bilge.Assert
          !!!, called at test/integration/API.hs:748:7 in main:API
        Use -p '/register too many push tokens/' to rerun this test only.
      share push token:                                            FAIL (0.12s)
        test/integration/API.hs:806:
        token mismatch
        expected: Token {tokenText = "1dbe67de-b5a8-4078-9c9a-dceddf2420b2"}
         but got: Token {tokenText = "NO_HEADER_VALUE"}
        Use -p '/share push token/' to rerun this test only.
      replace shared push token:                                   FAIL (0.14s)
        test/integration/API.hs:836:
        expected: [Token {tokenText = "ac46ee39-e8b1-47fb-acc5-420e065f42a2"}]
         but got: []
        Use -p '/replace shared push token/' to rerun this test only.

```

But there's no way that's related to changing export lists --- in the worst case, things wouldn't compile. Mind taking a look?

**Comment by fisx** [comment]
> @fisx I'm having a hard time getting CI to pass here:

ran the tests locally successfully.  i have no idea right now?

**Comment by jschaul** [comment]
```
#10 504.2 spar                             > /wire-server/services/spar/src/Spar/Sem/ScimTokenStore.hs:22:5: error:
#10 504.2 spar                             >     Not in scope: ‘getByTeam’
#10 504.2 spar                             >    |
#10 504.2 spar                             > 22 |     getByTeam,
#10 504.2 spar                             >    |     ^^^^^^^^^
```

**Comment by fisx** [comment]
045030b how could this escape me when I ran the tests locally?!  And how did you not catch this before pushing?  Interesting.  :)

**Review by fisx — APPROVED** [review]

**Review by mdimjasevic — APPROVED** [review]
Nothing controversial here!

**Pull request merged**
