### PR TITLE
Bump handlebars.js to 4.1.0.

### PR DESCRIPTION
**Pull request by fisx**
https://www.npmjs.com/advisories/755

thanks @ffflorian!

(not tested.  is there a way to test this before staging?)

### CODE REVIEW

**Comment by neongreen** [comment]
I don't see how this would work. Where would `handlebars-4.1.0.js` come from?

**Comment by neongreen** [comment]
https://github.com/wireapp/wire-server/blob/develop/services/nginz/Makefile#L102-L110

Swagger files are downloaded here.

The minor version of Swagger would probably need to be updated (if they are still doing security patches for the version we're using).

**Comment by fisx** [comment]
good point.  i guess we could fetch it from [here](https://github.com/wycats/handlebars.js/archive/v4.1.0.tar.gz)?

not sure about all the stuff that could go wrong there, though.

**Comment by fisx** [comment]
Given we're delivering this [in production](https://prod-nginz-https.wire.com/swagger-ui/), and given I don't really know how this works, I don't feel confident enough to decide the issue does not affect us.

If anybody can, feel free to close.

**Comment by fisx** [comment]
(swagger-ui doesn't have a fix yet, i just checked.)

**Comment by fisx** [comment]
the bug does not affect us here.

**Pull request closed without merging**
