### PR TITLE
Do not buffer stdout in integration tests.

### PR DESCRIPTION
**Pull request by fisx**
inspired by http://www.perkin.org.uk/posts/how-to-fix-stdio-buffering.html

### CODE REVIEW

**Comment by fisx** [comment]
actually, i'm not sure this works.  i'll will take another look...

**Comment by fisx** [comment]
In alpine-builder, *before* adding GNU sed:

```
bash-4.4# ./start-services-only.sh
Running tests using mocked AWS services


WARNING: log output is buffered and may not show on your screen!




WARNING: log output is buffered and may not show on your screen!




WARNING: log output is buffered and may not show on your screen!




WARNING: log output is buffered and may not show on your screen!




WARNING: log output is buffered and may not show on your screen!




WARNING: log output is buffered and may not show on your screen!




WARNING: log output is buffered and may not show on your screen!


[spar] NoBuffering
[spar] NoBuffering
[galley] I, logger=cassandra.galley, Known hosts: [datacenter1:rack1:127.0.0.1:9042]
[gundeck] I, logger=cassandra.gundeck, Known hosts: [datacenter1:rack1:127.0.0.1:9042]
[spar] D, logger=cassandra.spar, Connecting to 127.0.0.1:9042
[spar] I, logger=cassandra.spar, Known hosts: [datacenter1:rack1:127.0.0.1:9042]
[spar] I, logger=cassandra.spar, New control connection: datacenter1:rack1:127.0.0.1:9042#39
[spar] D, logger=cassandra.spar, Connection established: datacenter1:rack1:127.0.0.1:9042#40
[galley] I, logger=cassandra.galley, New control connection: datacenter1:rack1:127.0.0.1:9042#11
[gundeck] I, logger=cassandra.gundeck, New control connection: datacenter1:rack1:127.0.0.1:9042#11
all services are up!
(This will hang, Control+C to close.)
Now you can manually curl them or start an integration test executable manually with e.g.
(first cd to a service dir for correct working directory)
  cd services/brig && ../../dist/brig-integration -s brig.integration.yaml -i ../integration.yaml
^C[gundeck] I, Listening on 0.0.0.0:8086
/wire-server/services/integration.sh: line 76: 13797 Terminated              "${TOP_LEVEL}/dist/${service}" -c "${service}${instance}.integration${integration_file_extension}"
/wire-server/services/integration.sh: line 76: 13809 Terminated              "${TOP_LEVEL}/dist/${service}" -c "${service}${instance}.integration${integration_file_extension}"
[cannon] I, Listening on 127.0.0.1:8083
[cannon] I, Listening on 127.0.0.1:8183
[cargohold] I, Listening on 0.0.0.0:8084
[gundeck] I, Shutting down ...
[galley] I, Listening on 127.0.0.1:8085
[spar] I, Listening on 0.0.0.0:8088
```

in alpine-builder, *after* adding GNU sed:

```
bash-4.4# ./start-services-only.sh
Running tests using mocked AWS services
[cannon] I, Listening on 127.0.0.1:8083
[cannon] I, Listening on 127.0.0.1:8183
[spar] NoBuffering
[spar] NoBuffering
[galley] I, logger=cassandra.galley, Known hosts: [datacenter1:rack1:127.0.0.1:9042]
[galley] I, logger=cassandra.galley, New control connection: datacenter1:rack1:127.0.0.1:9042#11
[cargohold] I, Listening on 0.0.0.0:8084
[spar] D, logger=cassandra.spar, Connection established: datacenter1:rack1:127.0.0.1:9042#40
[spar] D, logger=cassandra.spar, Connecting to 127.0.0.1:9042
[gundeck] I, logger=cassandra.gundeck, Known hosts: [datacenter1:rack1:127.0.0.1:9042]
[gundeck] I, logger=cassandra.gundeck, New control connection: datacenter1:rack1:127.0.0.1:9042#11
[galley] I, Listening on 127.0.0.1:8085
[spar] I, logger=cassandra.spar, Known hosts: [datacenter1:rack1:127.0.0.1:9042]
[spar] I, logger=cassandra.spar, New control connection: datacenter1:rack1:127.0.0.1:9042#39
[spar] I, Listening on 0.0.0.0:8088
[gundeck] I, Listening on 0.0.0.0:8086
all services are up!
(This will hang, Control+C to close.)
Now you can manually curl them or start an integration test executable manually with e.g.
(first cd to a service dir for correct working directory)
  cd services/brig && ../../dist/brig-integration -s brig.integration.yaml -i ../integration.yaml
^C/wire-server/services/integration.sh: line 76: 13611 Terminated              "${TOP_LEVEL}/dist/${service}" -c "${service}${instance}.integration${integration_file_extension}"
[gundeck] I, Shutting down ...
bash-4.4# 
```

After this change, you either get a warning that you shouldn't rely on getting all the log (useful!), or you get all the logs.  Note how after ^C, you don't see cargohold telling you that it's listening, that line has already been logged above.

**Comment by fisx** [comment]
ready for review!

**Comment by ChrisPenner** [comment]
I suspect this is going to always be unbuffered on Mac (builtin sed on mac don't work so good); Mind if I add a quick patch for the mac version before you merge?

**Comment by fisx** [comment]
> I suspect this is going to always be unbuffered on Mac (builtin sed on mac don't work so good); Mind if I add a quick patch for the mac version before you merge?

please do!

**Pull request merged**
