### PR TITLE
new version of the ha diagram, from sqpit1518 jira ticket

### PR DESCRIPTION
**Pull request by arthurwolf**
## Checklist

 - [ ] Add a new entry in an appropriate subdirectory of `changelog.d`
 - [ ] Read and follow the [PR guidelines](https://docs.wire.com/developer/developer/pr-guidelines.html)

### CODE REVIEW

**Comment by arthurwolf** [comment]
forgot the title and only saw it once checking the actual PR, made a commit with the change

**Comment by arthurwolf** [comment]
architecture-server-ha

**Comment by arthurwolf** [comment]
architecture-server-ha

made the changes requested by julia and sebastian, ready for merging.

**Comment by julialongtin** [comment]
Redis is only on one node, not three.

**Review by julialongtin — APPROVED** [review]

**Pull request merged**
