### PR TITLE
Fix assertion after #1956

### PR DESCRIPTION
**Pull request by pcapriotti**
Fix failing test on develop caused by merging #1956 and #1973.

No CHANGELOG entry.

## Checklist

 - [x] The **PR Title** explains the impact of the change.
 - [x] The **PR description** provides context as to why the change should occur and what the code contributes to that effect. This could also be a link to a JIRA ticket or a Github issue, if there is one.

### CODE REVIEW

**Comment by fisx** [comment]
> No CHANGELOG entry.

Again, release notes would be more correct if the release notes entries for the old PR would contain both PRs in brackets now.

**Review by fisx — APPROVED** [review]

**Comment by fisx** [comment]
```
    RealAWS
      resumable
        small:              OK (0.03s)
        large:              FAIL (1.52s)
          test/integration/API/V3.hs:380:
          status
          expected: Status {statusCode = 204, statusMessage = "No Content"}
           but got: Status {statusCode = 500, statusMessage = "Internal Server Error"}
```

not sure if that's related.  i'll run this again!

**Comment by pcapriotti** [comment]
> Again, release notes would be more correct if the release notes entries for the old PR would contain both PRs in brackets now.

Done on both PRs, but of course they'll conflict with each other.

**Comment by pcapriotti** [comment]
> ```
>     RealAWS
>       resumable
>         small:              OK (0.03s)
>         large:              FAIL (1.52s)
>           test/integration/API/V3.hs:380:
>           status
>           expected: Status {statusCode = 204, statusMessage = "No Content"}
>            but got: Status {statusCode = 500, statusMessage = "Internal Server Error"}
> ```
> 
> not sure if that's related. i'll run this again!

This is a flake that has appeared recently. I don't know if it's related to the recent changes to cargohold. Seems unlikely.

**Pull request merged**
