### PR TITLE
Use URLs for snapshots; switch fork repos

### PR DESCRIPTION
**Pull request by neongreen**
Now wire-1.2.yaml contains a link to wire-1.1.yaml, and not just a relative path.

Without this PR we can't use wire-server snapshots in other repos, because Stack is not smart enough to fetch snapshots based on relative paths.

From this point on, the resolver/snapshot files *actually* have to be immutable.

This PR will cause another "copying precompiled package" cascade. @fisx sorry!

### CODE REVIEW

**Comment by neongreen** [comment]
@ChrisPenner I added a readme.

**Comment by neongreen** [comment]
This won't/can't pass the CI.

**Comment by neongreen** [comment]
Since this PR breaks snapshot caching anyway, I've also updated snapshot files to point at @wireapp forks instead of mine and Tiago's forks. The only repo left to transfer is https://github.com/tiago-loureiro/haskell-multihash.

**Comment by tiago-loureiro** [comment]
> Since this PR breaks snapshot caching anyway, I've also updated snapshot files to point at @wireapp forks instead of mine and Tiago's forks. The only repo left to transfer is https://github.com/tiago-loureiro/haskell-multihash.

Done

**Pull request merged**
