### PR TITLE
Cleanup: incoherent functions for response body parsing.

### PR DESCRIPTION
**Pull request by fisx**
The first commit gives a good idea of what I'm doing here.

### CODE REVIEW

**Comment by fisx** [comment]
Ready for review!

**Comment by fisx** [comment]
(The CI error should be fixed with this: https://github.com/wireapp/wire-server/pull/848)

**Comment by fisx** [comment]
> In the usage, it seems you replaced all existing instances of decodeBody with either `responseJsonMaybe` or `responseJsonThrow ErrorCall`.  [...]

`Maybe` is an instance of `MonadThrow`, so you can do this:

```haskell
decodeBody :: MonadThrow m => m ()
decodeBody = undefined

alsoDecodeBody :: Maybe ()
alsoDecodeBody = decodeBody
```

This can be very confusing if you expect `throw` to actually do something exception-y, but instead it'll just discard the exception value and return `Nothing`.

Before this PR, there was just one `decodeBody` function in this region of the test suite, and it was used polymorphically for both throwing exceptions and returning `Nothing`.  I also found this confusing, and when I realized it I decided I'd better specialize the `Nothing` part.

> Can you add a helper for `responseJsonThrow ErrorCall` or adapt the responseJsonThrow one to take `ErrorCall` as an argument by default (to allow for less typing when using this, especially in tests)

will do, thanks for insisting.  i think I thought that would be a good idea, but then i was too lazy.  :)

**Comment by jschaul** [comment]
> `Maybe` is an instance of `MonadThrow`, so you can do this:
> 
> ```haskell
> decodeBody :: MonadThrow m => m ()
> decodeBody = undefined
> 
> alsoDecodeBody :: Maybe ()
> alsoDecodeBody = decodeBody
> ```
> 
> This can be very confusing if you expect `throw` to actually do something exception-y, but instead it'll just discard the exception value and return `Nothing`.
> 
> Before this PR, there was just one `decodeBody` function in this region of the test suite, and it was used polymorphically for both throwing exceptions and returning `Nothing`. I also found this confusing, and when I realized it I decided I'd better specialize the `Nothing` part.

:bulb: Aha! Thanks for the explanation, I had been wondering why `decodeBody` sometimes gave a Maybe and sometimes threw an exception. I think the refactored Code is much clearer now. Thanks!

**Pull request merged**
