### PR TITLE
docker images: Add container utilities

### PR DESCRIPTION
**Pull request by jschaul**
## Checklist

 - [x] Add a new entry in an appropriate subdirectory of `changelog.d`
 - [x] Read and follow the [PR guidelines](https://docs.wire.com/developer/developer/pr-guidelines.html)

### CODE REVIEW

**Review by flokli — COMMENTED** [review]
It's very hard to see what this PR is actually changing. Can you move the code formatting into a separate commit?

**Comment by jschaul** [comment]
> It's very hard to see what this PR is actually changing. Can you move the code formatting into a separate commit?

sorry I can't easily, as my editor now reformats nix code. Perhaps we should include a formatter for nix code in wire-server, and reformat all nix code once, to not have this issue going forward.

But you can tick **"Hide Whitespace"** here:

whitespace

**Comment by jschaul** [comment]
Rebased, no reformatting anymore.

**Comment by flokli** [comment]
Check https://github.com/wireapp/wire-server/pull/2831, which ensures .nix code is consistently formatted.

**Review by flokli — APPROVED** [review]

**Pull request merged**
