### PR TITLE
Saml IDP: allow to re-use previously used issuer names.

### PR DESCRIPTION
**Pull request by fisx**
**Bug:** If an IdP issuer is changed from A to B and then back to A, the second update fails with the message "A alredy in use".  This is technically correct, since we keep old idp configs around to allow gradual migration of users from old issuer name to new.  

**Fix:** IdPs should be allowed to reuser their *own* issuer names.

**Technical details:** [from memory, I probably should double-check] the idp keeps a list of old idp issuer names around.  If a user tries to auth with a new issuer name, but cannot be found in `spar.user`, we pull the list of old idp issuer names, and do lookups in `spar.user` by those.  If we find a user, it is because that user has not been seen since before one or more idp metadata updates, and the entry in `spar.user` is outdated.  We fix the entry and return the user.

Internal issue: https://wearezeta.atlassian.net/browse/SQSERVICES-537

## Checklist

 - [x] Title of this PR explains the impact of the change.
 - [x] The description provides context as to why the change should occur and what the code contributes to that effect. This could also be a link to a JIRA ticket or a Github issue, if there is one.
 - [x] The CHANGELOG.md file in the *Unreleased* section has been updated to explain the change which will be included in the release notes.
 - [x] If a component uses a new or changed internal endpoint of another component, this is mentioned in the CHANGELOG.md.
- [x] If this PR creates a new endpoint, or adds a new configuration flag, the endpoint / config-flag checklist (see Wire-employee only backend [wiki page](https://github.com/zinfra/backend-wiki/wiki/Checklists)) has been followed.

### CODE REVIEW

**Comment by fisx** [comment]
```
Spar.API
  PUT /identity-providers/:idp
    issuer changed to one that already existed in the same team in the past (but has been updated away)
      changes back to the old one and keeps the new in the `old_issuers` list. FAILED [1]

Failures:

  test-integration/Test/Spar/APISpec.hs:770:20: 
  1) Spar.API, PUT /identity-providers/:idp, issuer changed to one that already existed in the same team in the past (but has been updated away), changes back to the old one and keeps the new in the `old_issuers` list.
       expected: 200
        but got: 400
```

**Comment by fisx** [comment]
spar integration tests pass locally.

**Comment by akshaymankar** [comment]
The new CI pipeline picked this PR up by mistake, I have stopped it, let me know if something is off here.

**Review by smatting — APPROVED** [review]

**Comment by fisx** [comment]
> The new CI pipeline picked this PR up by mistake, I have stopped it, let me know if something is off here.

i don't think it was a mistake.  now i don't have a valid ci run on the last commit of this PR, so i'll just poke it again.  please leave it running!  :)

**Pull request merged**
