### PR TITLE
Documentation: add nix cache instructions

### PR DESCRIPTION
**Pull request by isovector**
## Checklist

 - [ ] Add a new entry in an appropriate subdirectory of `changelog.d`
 - [x] Read and follow the [PR guidelines](https://docs.wire.com/developer/developer/pr-guidelines.html)

### CODE REVIEW

**Review by stephen-smith — APPROVED** [review]
There's already docs for this in docs/src/how-to/install/dependencies.rst (listed as "Optional") and docs/src/developer/developer/dependencies.md (in the configuration), but I don't see much disadvantage to mentioning it here, as well.

**Comment by isovector** [comment]
Is that document linked from the main README? Maybe I missed it?

**Comment by stephen-smith** [comment]
The dependencies.rst isn't linked from anywhere I can see.  The dependencies.md is linked from how-to.md in the same directory, but how-to.md isn't linked from anywhere.  So, I do not see a link chain from README.md to either of those locations.

**Comment by sysvinit** [comment]
We have some internal documentation for Nix and Cachix setup in the README for `cailleach` (which I don't think @isovector is able to see). I think this might have come up once or twice in the past, but as the instructions are relevant both for `wire-server` and `cailleach`, it might be worth moving these docs into the public repo so they're visible to external contributors.

**Pull request merged**
