### PR TITLE
bump hsaml2 dep

### PR DESCRIPTION
**Pull request by fisx**
https://github.com/wireapp/hsaml2/pull/4

### CODE REVIEW

**Comment by fisx** [comment]
curiously, `make` on this branch makes stack (1.9.1) unregister 383 packages, and then re-register all of them without compiling anything.  this takes ~10 minutes on my laptop.

**Comment by neongreen** [comment]
But only once, right?

**Comment by neongreen** [comment]
It's kinda the expected behavior when creating a new snapshot. Takes less
than 10 minutes on my machine though :/

**Pull request merged**
