### PR TITLE
Fix stack yaml

### PR DESCRIPTION
**Pull request by fisx**

### CODE REVIEW

**Comment by neongreen** [comment]
That's unfortunate timing :( The alpine-builder has *almost* finished.

I will kill the Concourse jobs created by this PR and then ask you to push an empty commit or amend this one.

**Comment by neongreen** [comment]
Hm, or actually I should be able to just restart the job for you.

**Comment by fisx** [comment]
> Hm, or actually I should be able to just restart the job for you.

Thanks!  :-)  (in case it matters, I won't need this before Monday.  Good night..)

**Comment by neongreen** [comment]
@fisx do you mind if I also merge this after the tests pass?

**Pull request merged**
