### PR TITLE
Fix potential pagination bug

### PR DESCRIPTION
**Pull request by smatting**

### CODE REVIEW

**Review by fisx — CHANGES_REQUESTED** [review]
What about [this comment](https://github.com/wireapp/wire-server/blob/2a6fbaa253850d7a79c5d05d8be5f84ee5279dd7/services/galley/src/Galley/Data.hs#L153-L163)?

**Comment by akshaymankar** [comment]
Can a test be added to see if this is indeed a bug or not?

**Comment by fisx** [comment]
> What about [this comment](https://github.com/wireapp/wire-server/blob/2a6fbaa253850d7a79c5d05d8be5f84ee5279dd7/services/galley/src/Galley/Data.hs#L153-L163)?

(it was unrelated.  the `ResultSet` abstraction can be used on any one page, but we still need the `Page` type for moving to the next page.  maybe `ResultSet` was not the best idea ever, it's at the very best confusing.)

**Comment by fisx** [comment]
(it's not a bug, the change has no impact on behavior.  but it's more clear this way.)

**Review by fisx — APPROVED** [review]

**Pull request merged**
