### PR TITLE
replace all instances of example.com with default.domain

### PR DESCRIPTION
**Pull request by arthurwolf**
manually going over all of them now.

(note: See WPB-2621 )

## Checklist

 - [ ] Add a new entry in an appropriate subdirectory of `changelog.d`
 - [ ] Read and follow the [PR guidelines](https://docs.wire.com/developer/developer/pr-guidelines.html)

### CODE REVIEW

**Review by smatting — CHANGES_REQUESTED** [review]
Replacing all instances will not work. We use `example.com` `b.example.com` `c*.example.com` as domains for our integration tests. We can't change them easily.

Maybe change only in `docs/`?

**Review by flokli — CHANGES_REQUESTED** [review]
Also NAK on the general direction of this PR.

https://www.rfc-editor.org/rfc/rfc2606.html describes what domain names or TLDs to use for testing/documentation examples, and example.com is among them, while default.domain certainly is not.

**Comment by arthurwolf** [comment]
Re-tooling this PR: it will now be only about modifications to the docs, there will be a separate ticket (and maybe PR later) for deeper work.

**Comment by arthurwolf** [comment]
After internal discussions, also changing the demain to "wire.example"

**Comment by rohan-wire** [comment]
> Also NAK on the general direction of this PR.
> 
> https://www.rfc-editor.org/rfc/rfc2606.html describes what domain names or TLDs to use for testing/documentation examples, and example.com is among them, while default.domain certainly is not.

a.example, b.example, c.example, a.test, b.test, are all appropriate domains for documentation.

I thought we agreed that backends with no local domain name should be configured with `local.invalid`?

**Pull request closed without merging**
