### PR TITLE
Sanitize `delete-cache-on-linker-errors` make target

### PR DESCRIPTION
**Pull request by supersven**
`dist-newstyle`: The directory name depends on the cabal version. `cabal
clean` does the job (using the tool itself to manage it's cache).

`~/.cabal`: We shouldn't delete the whole folder as it may contain a manually tweaked `config` file. Deleting `~/.cabal/store` should be sufficient.

E.g. my `~/.cabal/config` contains this to get docs for all packages in Haskell Language Server:
```cabal
program-default-options
  ghc-options: -haddock
```

## Checklist

 - [X] The **PR Title** explains the impact of the change.
 - [X] The **PR description** provides context as to why the change should occur and what the code contributes to that effect. This could also be a link to a JIRA ticket or a Github issue, if there is one.
 - [X] If this PR changes development workflow or dependencies, they have been A) automated and B) documented under docs/developer/. All efforts have been taken to minimize development setup breakage or slowdown for co-workers.
 - [X] **changelog.d** contains the following bits of information ([details](https://github.com/wireapp/wire-server/blob/develop/docs/developer/changelog.md)):
   - [X] A file with the changelog entry in one or more suitable sub-sections. The sub-sections are marked by directories inside `changelog.d`.

### CODE REVIEW

**Review by smatting — APPROVED** [review]

**Comment by sysvinit** [comment]
I have a soft nack against this `make` target, as I have my environment set up with the `CABAL_DIR` environment variable so that cabal stores its data somewhere other than `~/.cabal`. However, I strongly suspect I'm a small minority here, so I won't block the PR, as it's easy enough for me to do a cache bust by hand when necessary.

**Comment by fisx** [comment]
> I have a soft nack against this `make` target, as I have my environment set up with the `CABAL_DIR` environment variable so that cabal stores its data somewhere other than `~/.cabal`. However, I strongly suspect I'm a small minority here, so I won't block the PR, as it's easy enough for me to do a cache bust by hand when necessary.

gotta protect minorities!!  :)

also, isn't there a simple change that would honor `$CABAL_DIR` and do it right for all of us *and* for you?

**Comment by sysvinit** [comment]
> also, isn't there a simple change that would honor `$CABAL_DIR` and do it right for all of us *and* for you?

For sure -- I was mostly meaning to point out that the `make` target as written is incompatible with setting `CABAL_DIR`, but it doesn't need to be perfect here and now.

**Comment by supersven** [comment]
Thanks for bringing this up, @sysvinit !

Would this work for you: https://github.com/wireapp/wire-server/pull/2623/commits/8101c5baf866a5fc33a048a4ff03067c6db93c62 ?

**Review by jschaul — APPROVED** [review]

**Comment by smatting** [comment]
Sorry for the merge commit @supersven . I used GH's "resolve conflicts" feature after merging https://github.com/wireapp/wire-server/pull/2621 - feel free to throw away and rebase

**Comment by supersven** [comment]
> Sorry for the merge commit @supersven . I used GH's "resolve conflicts" feature after merging #2621 - feel free to throw away and rebase

No worries, @smatting . I hope it will just vanish when I `squash` for merge.

**Comment by sysvinit** [comment]
> Thanks for bringing this up, @sysvinit !
> 
> Would this work for you: [8101c5b](https://github.com/wireapp/wire-server/commit/8101c5baf866a5fc33a048a4ff03067c6db93c62) ?

Yeah, that looks good.

**Pull request merged**
