### PR TITLE
[WPB-7161] Generalise catchErrors middleware

### PR DESCRIPTION
**Pull request by battermann**
## Checklist

 - [x] Add a new entry in an appropriate subdirectory of `changelog.d`
 - [x] Read and follow the [PR guidelines](https://docs.wire.com/developer/developer/pr-guidelines.html)

### CODE REVIEW

**Review by pcapriotti — APPROVED** [review]

**Comment by mdimjasevic** [comment]
Is this done for https://wearezeta.atlassian.net/browse/WPB-7161?

**Comment by pcapriotti** [comment]
> Is this done for https://wearezeta.atlassian.net/browse/WPB-7161?

I think so.

**Comment by mdimjasevic** [comment]
Great! I'm introducing request IDs in all the services and then I'll leave the federator to you as part of this PR.

**Comment by mdimjasevic** [comment]
I tagged the PR with a ticket number in the title so it gets tracked automatically by Jira. Let me know if this is a wrong ticket!

**Pull request merged**
