### PR TITLE
Release/2019 05 02

### PR DESCRIPTION
**Pull request by ChrisPenner**
## Documentation changes

* Improved Cassandra documentation in `docs/README.md`
* Improved documentation on SCIM storage in `docs/README.md`
* Improved documentation on SCIM Tokens in `docs/reference/provisioning/scim-token.md`

## Bug fixes

* Sanitize metric names to be valid prometheus names in metrics-core
* Add missing a `.git` suffix on gitlab dependencies in stack.yaml
* Time bounds checks now allow 60s of tolerance; this is helpful in cases of drifting clocks (#730)

## Features

* Services now provide Prometheus metrics on `/i/metrics`
* Garbage Collection and memory statistics are available alongside other prometheus metrics

## Internal Changes

* Alpine Builder is no longer built with `--profile`
* SCIM users now have an additional wire-specific schema attached.

## Changes (potentially) requiring action
* `/i/monitoring` is *DEPRECATED*. Please use prometheus metrics provided by `/i/metrics` instead.
* On password reset the new password must be different than the old one
* Stern is now available as a new tool for performing administrative tasks via API (#720)
* SCIM handler errors are now reported according to SCIM error schema (#575)

### CODE REVIEW

**Comment by fisx** [comment]
- I can't find https://github.com/wireapp/wire-server/pull/575, https://github.com/wireapp/wire-server/pull/730 in the release notes?  At least #730 is quite relevant.
- I liked the fact that the release notes referenced the relevant PRs in the last releases.  We can skip it this time, but it would to have that back in the next release.

**Comment by ChrisPenner** [comment]
@fisx 575 was listed under internal changes; I moved it to the public changes :)

Sorry I missed 730! It's been added 😄

**Comment by fisx** [comment]
@jschaul any reason we shouldn't include https://github.com/wireapp/wire-server/pull/725?

**Comment by jschaul** [comment]
> @jschaul any reason we shouldn't include #725?

Don't release untested changes. That PR isn't merged because the upstream way of building docker images changed and needs updating/testing first (which I only saw after I made that PR).

**Pull request merged**
