### PR TITLE
Always build benchmarks

### PR DESCRIPTION
**Pull request by neongreen**

### CODE REVIEW

**Comment by fisx** [comment]
I'll see if I can fix it quickly.

**Comment by fisx** [comment]
Hum, not sure what to do.  `import Prelude` makes it compile, but I don't think that's what you want.

Also, I got this when running `make` in `services/gundeck`:

```
Warning: Unable to find a known candidate for the Cabal entry V3, but did find: 
         * V3.hs~ If you are using a custom preprocessor for this module with its own file extension, consider adding the
         file(s) to your .cabal under extra-source-files.
```

?!  `V3.hs` is where it should be.

**Comment by neongreen** [comment]
I'll look at it tomorrow or at some point sometime

**Comment by neongreen** [comment]
It should work after the rebase. Regarding `V3.hs~`: it might be a temp file from your editor, try deleting it.

**Pull request merged**
