### PR TITLE
Handle async exceptions so Control-C works as expected

### PR DESCRIPTION
**Pull request by elland**
Integration tests weren't being killed on control-c, when investigating a proposed fix we realised that tests were running sequentially on the main thread, causing the issue with exception handling. Since running them in parallel increases flakiness, I'm holding off on correcting this until we do some of the mitigation work we have planned.

### CODE REVIEW

**Comment by pcapriotti** [comment]
On second thought, maybe we need to limit the number of concurrent tests. Otherwise we might try to use too many file descriptors or overwhelm some of the services.

**Comment by MangoIV** [comment]
https://hackage.haskell.org/package/unliftio-0.2.25.0/docs/UnliftIO-Async.html#v:pooledForConcurrentlyN

**Comment by MangoIV** [comment]
I used this successfully in similar situations

**Comment by elland** [comment]
@MangoIV the problem with the UnliftIO alternative is that the async exception doesn't properly kill the threads, leaving us with the same IO leakage as before. One option is to keep the async handler in place, another might be something like async-pooled. 🤔

**Review by pcapriotti — APPROVED** [review]

**Comment by elland** [comment]
@pcapriotti @MangoIV it seems running the tests in parallel at the moment increase our flakiness too much. I would for now just fix the Control-C handling and wait until our other flakiness mitigating changes to parallelise the tests.

**Comment by pcapriotti** [comment]
That's fine, but we probably want to look into running the tests asynchronously at some point.

**Pull request merged**
