### PR TITLE
nix: Pin openssl to 1.1

### PR DESCRIPTION
**Pull request by akshaymankar**
https://wearezeta.atlassian.net/browse/SQPIT-1478

## Checklist

 - [x] ~Add a new entry in an appropriate subdirectory of `changelog.d`~ No changelog, last release used openssl 1.1 anyway.
 - [x] Read and follow the [PR guidelines](https://docs.wire.com/developer/developer/pr-guidelines.html)

### CODE REVIEW

**Comment by sysvinit** [comment]
Alternatively, would something like this work?

```patch
diff --git a/nix/manual-overrides.nix b/nix/manual-overrides.nix
index 0cecced51..3a38a4435 100644
--- a/nix/manual-overrides.nix
+++ b/nix/manual-overrides.nix
@@ -1,4 +1,4 @@
-{ libsodium, protobuf, hlib, mls-test-cli }:
+{ libsodium, protobuf, hlib, mls-test-cli, openssl }:
 # FUTUREWORK: Figure out a way to detect if some of these packages are not
 # actually marked broken, so we can cleanup this file on every nixpkgs bump.
 hself: hsuper: {
@@ -58,4 +58,6 @@ hself: hsuper: {
 
   # Make hoogle static to reduce size of the hoogle image
   hoogle = hlib.justStaticExecutables hsuper.hoogle;
+
+  HsOpenSSL = hsuper.HsOpenSSL.override { inherit openssl; };
 }
diff --git a/nix/wire-server.nix b/nix/wire-server.nix
index 03005e5bc..c3270518e 100644
--- a/nix/wire-server.nix
+++ b/nix/wire-server.nix
@@ -123,6 +123,7 @@ let lib = pkgs.lib;
       ];
     manualOverrides = import ./manual-overrides.nix (with pkgs; {
       inherit hlib libsodium protobuf mls-test-cli;
+      openssl = openssl_1_1;
     });
 
     executables = hself: hsuper:
```

After applying this patch to current `develop`, I get this:

```
molly on flux ~/s/w/wire-server> nix-build --no-out-link -A wireServer.haskellPackagesUnoptimizedNoDocs.brig ./nix -j4
# ... lots of Haskell compilation happens here ...
/nix/store/rjbbnpnjqhni8zi895hkql5khvppch4b-brig-2.0
molly on flux ~/s/w/wire-server> ldd /nix/store/rjbbnpnjqhni8zi895hkql5khvppch4b-brig-2.0/bin/* | grep libssl
	libssl.so.1.1 => /nix/store/a4g2mals99rhsq1q7rydszz5b5bhzbm3-openssl-1.1.1q/lib/libssl.so.1.1 (0x00007f2ecf625000)
	libssl.so.1.1 => /nix/store/a4g2mals99rhsq1q7rydszz5b5bhzbm3-openssl-1.1.1q/lib/libssl.so.1.1 (0x00007fdd9d3d5000)
	libssl.so.1.1 => /nix/store/a4g2mals99rhsq1q7rydszz5b5bhzbm3-openssl-1.1.1q/lib/libssl.so.1.1 (0x00007fd0af9a1000)
	libssl.so.1.1 => /nix/store/a4g2mals99rhsq1q7rydszz5b5bhzbm3-openssl-1.1.1q/lib/libssl.so.1.1 (0x00007fe9af4b8000)
```

If we have other Haskell dependencies which link against OpenSSL directly then we'd need to override them in the overlay similarly, but this would avoid doing a world rebuild of Nixpkgs.

**Comment by sysvinit** [comment]
I don't understand all the overlay machinery here well enough to write this myself, but maybe a more robust solution here would be to add another overlay function in `wire-server.nix` which overrides OpenSSL for *all* the Haskell libraries which depend on it, instead of manually adding overrides for every library we come across which needs OpenSSL.

**Comment by akshaymankar** [comment]
@sysvinit feel free to push your experiments to this branch. Maybe we can examine the docker images to see if any of them contain openssl 3.

**Comment by sysvinit** [comment]
> Maybe we can examine the docker images to see if any of them contain openssl 3.

Either we extract the docker images, or we identify the derivations which are included in the docker images, and then analyse their transitive dependencies to check whether openssl 3 occurs in any of the closures included in the docker images.

**Comment by sysvinit** [comment]
I pushed a commit with the patch I suggested earlier onto this branch; it's plausible there are Haskell packages other than `HsOpenSSL` which FFI to openssl, in which case we'd need to add a similar override for those packages. If CI is happy with this commit, we should download the build outputs from cachix and take a look at the dependency closures to figure out if openssl 3 still gets pulled in anywhere.

**Comment by sysvinit** [comment]
The integration tests are still running at the time of writing, but the compile run has passed. I came up with the following one-liner to:

- grep the build logs for this build run to find lines from the cachix client uploading derivations to the cachix store
- download these store paths to my laptop
- enumerate the dependency closure of these paths
- grep this list of store paths for openssl

Noting that this is build 138 of the `wire-server-compile-nix` job in the `wire-server-pr`:

```
molly on flux ~/s/w/c/w/ci> nix-store --query --requisites -f $(fly -t ops watch --job wire-server-pr/wire-server-compile-nix --build 138 | grep -Fi 'compressing and pushing' | cut -d' ' -f4) | grep openssl
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/a4g2mals99rhsq1q7rydszz5b5bhzbm3-openssl-1.1.1q
/nix/store/0x9q30rk07fdfqqlih040nqh2z2pn6bb-openssl-1.1.1q-bin
/nix/store/jcg80dha6a54zg543xpmz56z694cld8d-openssl-1.1.1q-dev
/nix/store/93bw29rjl3qhqv4gf5qcfdi9xxaxl60m-http-client-openssl-0.3.1.0-doc
/nix/store/f4r717cz1qf72iqmm7ihlz869g6irbk5-http-client-openssl-0.3.1.0
```

Alternatively: enumerating all the files contained in the closure of these paths, and grep for `libssl`:

```
molly on flux ~/s/w/c/w/ci> find -L $(nix-store --query --requisites -f $(fly -t ops watch --job wire-server-pr/wire-server-compile-nix --build 138 | grep -Fi 'compressing and pushing' | cut -d' ' -f4)) -type f | grep libssl
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/a4g2mals99rhsq1q7rydszz5b5bhzbm3-openssl-1.1.1q/lib/libssl.so.1.1
/nix/store/a4g2mals99rhsq1q7rydszz5b5bhzbm3-openssl-1.1.1q/lib/libssl.so
/nix/store/jcg80dha6a54zg543xpmz56z694cld8d-openssl-1.1.1q-dev/lib/pkgconfig/libssl.pc
```

**Review by sysvinit — APPROVED** [review]
Full steam ahead!

**Pull request merged**
