### PR TITLE
Upgrade polysemy to v1.7.0.0

### PR DESCRIPTION
**Pull request by isovector**
While investigating why #1917 was so slow to compile, I dug into the polysemy internals and found two significant improvements. These are https://github.com/polysemy-research/polysemy/pull/428 and https://github.com/polysemy-research/polysemy/pull/429, now released as `polysemy-1.7.0.0`.

This PR upgrades wire to the latest version of `polysemy`, which greatly improves the core generated by polysemy. For example, `Galley.API.Public` sees the following changes:

```diff
-terms: 16,086
+terms: 14,170
-types: 7,910,353
+types: 6,471,281
-coercions: 13,919,222
+coercions: 5,388,391
-ppr core size: 951,956,810
+ppr core size: 358,626,018
```

## Checklist

 - [x] The **PR Title** explains the impact of the change.
 - [x] The **PR description** provides context as to why the change should occur and what the code contributes to that effect. This could also be a link to a JIRA ticket or a Github issue, if there is one.
 - [x] A file with the changelog entry in one or more suitable sub-sections. The sub-sections are marked by directories inside `changelog.d`.

### CODE REVIEW

**Comment by pcapriotti** [comment]
Looking at the reduction in the number of coercions, this looks great! I've tried it out and it feels a lot faster indeed. Unfortunately, it looks like polysemy-mock has been broken by this change, so we'll have to fix it (or consider dropping it) and bump its version before merging this PR. I will look into that.

**Comment by isovector** [comment]
Ah, stupid breakage on my part. I was cleaning up some of the internal TH, and didn't realize anyone would be depending on it. The patch should be one line in mocks.

**Comment by isovector** [comment]
Filed https://github.com/akshaymankar/polysemy-mocks/issues/2

**Review by mdimjasevic — APPROVED** [review]
I am not sure why, but a team test in Brig is failing. It doesn't seem to have anything to do with this PR.

**Comment by pcapriotti** [comment]
> I am not sure why, but a team test in Brig is failing. It doesn't seem to have anything to do with this PR.

Usual search order flake. I restarted it now.

**Comment by smatting** [comment]
Please also update the cabal files by running `cabal update  && ./tools/convert-to-cabal/generate.sh` after all packages are bumped.

**Comment by akshaymankar** [comment]
I published the new version to hackage: https://hackage.haskell.org/package/polysemy-mocks-0.2.0.0

**Comment by isovector** [comment]
> cabal update && ./tools/convert-to-cabal/generate.sh

Tried running `./tools/convert-to-cabal/generate.sh` on my end, and it failed due to not having nix installed. Would someone else mind running it for me? Cheers!

**Comment by mdimjasevic** [comment]
> > cabal update && ./tools/convert-to-cabal/generate.sh
> 
> Tried running `./tools/convert-to-cabal/generate.sh` on my end, and it failed due to not having nix installed. Would someone else mind running it for me? Cheers!

The commit 97f91f7 should take care of it.

**Review by pcapriotti — APPROVED** [review]

**Pull request merged**
