### PR TITLE
WPB-5312

### PR DESCRIPTION
**Pull request by battermann**
https://wearezeta.atlassian.net/browse/WPB-5312

## Checklist

 - [x] Add a new entry in an appropriate subdirectory of `changelog.d`
 - [x] Read and follow the [PR guidelines](https://docs.wire.com/developer/developer/pr-guidelines.html)

### CODE REVIEW

**Review by mdimjasevic — APPROVED** [review]
It looks good.

Have you tried it out? I hope this doesn't result in potentially incomprehensible logs.

**Comment by battermann** [comment]
> It looks good.
> 
> Have you tried it out? I hope this doesn't result in potentially incomprehensible logs.

Here is an example:

```
[federator@example.com] E, request=N/A, code=500, label=server-error, "Server Error. bääääääääääääääääääääääm CallStack (from HasCallStack):   error, called at src/Federator
/InternalServer.hs:111:8 in federator-1.0.0-inplace:Federator.InternalServer"  
```

**Review by smatting — APPROVED** [review]
Nice! Now, how can we solve the problem that we never have stack traces? In "integration" we solved the problem by attaching the stack trace to the exception object, iirc

**Comment by battermann** [comment]
> Nice! Now, how can we solve the problem that we never have stack traces? In "integration" we solved the problem by attaching the stack trace to the exception object, iirc

I am not sure, did you checkout the example above? It has a stack trace.

**Comment by smatting** [comment]
@battermann ah, didn't see. cool!

**Pull request merged**
