### PR TITLE
[FS-507] Improve a Connection Check Utility

### PR DESCRIPTION
**Pull request by mdimjasevic**
So far a connection checking (or belonging to a team) is done only for local users. This PR extends the utility to also cover remote users.

Tracked by https://wearezeta.atlassian.net/browse/FS-507.

## Checklist

 - [x] The **PR Title** explains the impact of the change.
 - [x] The **PR description** provides context as to why the change should occur and what the code contributes to that effect. This could also be a link to a JIRA ticket or a Github issue, if there is one.
 - [x] **changelog.d** contains the following bits of information ([details](https://github.com/wireapp/wire-server/blob/develop/docs/developer/changelog.md)):
   - [x] A file with the changelog entry in one or more suitable sub-sections. The sub-sections are marked by directories inside `changelog.d`.

### CODE REVIEW

**Comment by pcapriotti** [comment]
I'm not sure I like this change. The way things are right now, `ensureConnectedOrSameTeam` is called on the "local" code paths, while `ensureConnectedToRemotes` is called on the "remote" paths. So I'd rather keep them separated, instead of making the former call the latter.

**Comment by mdimjasevic** [comment]
> I'm not sure I like this change. The way things are right now, `ensureConnectedOrSameTeam` is called on the "local" code paths, while `ensureConnectedToRemotes` is called on the "remote" paths. So I'd rather keep them separated, instead of making the former call the latter.

If it's just a naming concern, then I'd rename `ensureConnectedOrSameTeam` to `ensureConnectedToLocalsOrSameTeam` (or alike) for consistency and to allow a general function that can check both local and remote users.

**Comment by pcapriotti** [comment]
It's not just naming. Either change the code that calls this function, so that there's no separate check for remotes, or leave things as they are. With this change, one of the two functions does both local and remote checks, while the other does only remote, and they are both used. This is not good.

**Comment by mdimjasevic** [comment]
In a discussion with Paolo we came to a conclusion this might have some performance penalty. Given that it doesn't improve the code much in other regards, I am abandoning this PR.

**Pull request closed without merging**
