### PR TITLE
Swagger docs.

### PR DESCRIPTION
**Pull request by fisx**
Related: https://github.com/zinfra/backend-issues/issues/1409

### CODE REVIEW

**Comment by fisx** [comment]
@tiago-loureiro I think you have a way of testing this before moving it to staging.  Wanna give me a hint?

**Comment by tiago-loureiro** [comment]
You can simply run: `INTEGRATION_USE_NGINZ=1 ./services/start-services-only.sh` and then go to http://localhost:8080/swagger-ui/

Looks good though

Screen Shot 2020-05-27 at 10 01 06

**Comment by dkovacevic** [comment]
👍

**Comment by fisx** [comment]
(we really need servant.)

**Pull request merged**
