### PR TITLE
 Brig Polysemy: Blacklist effects

### PR DESCRIPTION
**Pull request by isovector**
This PR exposes two new effects into Brig:

- `BlacklistStore`
- `BlacklistPhonePrefixStore`

previously housed in `Brig.Data.Blackist`.

In addition, it separates out the `CanonicalInterpreter` machinery into its own module, which is necessary for avoiding cyclical dependencies when doing large-scale effect work.

## Checklist

 - [x] The **PR Title** explains the impact of the change.
 - [x] The **PR description** provides context as to why the change should occur and what the code contributes to that effect. This could also be a link to a JIRA ticket or a Github issue, if there is one.
 - [x] **changelog.d** contains the following bits of information ([details](https://github.com/wireapp/wire-server/blob/develop/docs/developer/changelog.md)):
   - [x] A file with the changelog entry in one or more suitable sub-sections. The sub-sections are marked by directories inside `changelog.d`.

### CODE REVIEW

**Comment by isovector** [comment]
@mdimjasevic mind reviewing this? It's a blocker on all future brig effects. Thanks!

**Comment by mdimjasevic** [comment]
> @mdimjasevic mind reviewing this? It's a blocker on all future brig effects. Thanks!

I'll definitely review it! I'll do it tomorrow/Wednesday morning.

**Comment by mdimjasevic** [comment]
> @mdimjasevic mind reviewing this? It's a blocker on all future brig effects. Thanks!

I'll definitely review it! I'll do it tomorrow/Wednesday morning.

> > @mdimjasevic mind reviewing this? It's a blocker on all future brig effects. Thanks!
> 
> I'll definitely review it! I'll do it tomorrow/Wednesday morning.

I still haven't got around to it yet, but I also haven't forgotten it. I am sorry this has been taking so long.

**Review by mdimjasevic — APPROVED** [review]
Looks straightforward! Nice work!

The CI looks fishy again (only 2 checks passed and made the PR green, instead of 9 required), likely because you've created the PR, meaning it wouldn't run in CI. I'll take a look and if needed clone the PR so it goes through the CI.

**Comment by mdimjasevic** [comment]
I don't see how to re-trigger this properly in the CI so I'll close the PR and open a clone myself.

**Pull request closed without merging**
