### PR TITLE
[WIP]added default empty string to restund template

### PR DESCRIPTION
**Pull request by Veki301**
## Checklist

 - [ ] Add a new entry in an appropriate subdirectory of `changelog.d`
 - [ ] Read and follow the [PR guidelines](https://docs.wire.com/developer/developer/pr-guidelines.html)

### CODE REVIEW

**Comment by supersven** [comment]
Hey @Veki301 ,

Could you please explain what the benefits of having empty strings as default for `issuerRef`, `tls.key` and `tls.crt` are? AFAIK empty strings won't work here. Or, do they? :thinking:

**Comment by Veki301** [comment]
The wire-server-deploy CI is failing to build when these values are not provided. There is a hack in place there right now which we are trying to remove

**Comment by supersven** [comment]
> The wire-server-deploy CI is failing to build when these values are not provided. There is a hack in place there right now which we are trying to remove

Hey @Veki301 :wave: 

IMHO we shouldn't push `wire-server-deploy`'s odd needs into `wire-server`. Default values should be meaningful, the introduced empty strings likely won't work in a deployment to K8s.

Could we please close this PR?

**Comment by Veki301** [comment]
closing PR

**Pull request closed without merging**
