### PR TITLE
Bump hsaml2.

### PR DESCRIPTION
**Pull request by fisx**
https://github.com/wireapp/hsaml2/pull/10

Only trivial changes and changes in the test suite.

### CODE REVIEW

**Review by pcapriotti — CHANGES_REQUESTED** [review]
Could you also regerate cabal.project.freeze?

**Comment by fisx** [comment]
I tried `cabal freeze`, but [f925711](https://github.com/wireapp/wire-server/pull/2221/commits/f92571177cbd5e6cb6a3c625aa045be432a9577d) has too many changes, no?  Is there anything else I should do (instead)?

**Comment by pcapriotti** [comment]
`tools/convert-to-cabal/generate.sh` should do it

**Review by pcapriotti — APPROVED** [review]
Looks good!

**Pull request merged**
