### PR TITLE
Brig: Serve unified swagger of brig and galley

### PR DESCRIPTION
**Pull request by akshaymankar**
Doesn't work yet, because changes are pending in galley.

### CODE REVIEW

**Comment by jschaul** [comment]
Idea: Could the same be done for spar, too? Spar already gives back swagger 2.0.

**Comment by akshaymankar** [comment]
> Idea: Could the same be done for spar, too? Spar already gives back swagger 2.0.

Oh yeah, I forgot about spar. I will add it.

**Comment by akshaymankar** [comment]
Hmm, looks like brig never calls spar. This make it more complicated :(

**Comment by jschaul** [comment]
> Hmm, looks like brig never calls spar. This make it more complicated :(

Ah, really?

Hm, but spar calls both brig and galley. So maybe spar could gather the swaggers for the rest. But spar won't call gundeck and cargohold, so we'll anyway have to introduce a new service dependency for that.

The other option could be to write the swagger json(s) to a file when compiling, and move it into a file e.g. brig can read from disk in its container. Then no new http calls need to be made.

**Comment by akshaymankar** [comment]
> The other option could be to write the swagger json(s) to a file when compiling, and move it into a file e.g. brig can read from disk in its container. Then no new http calls need to be made.

If we move the API types to `wire-api`, brig can just have the swagger, we won't have to do any changes to our build system

**Comment by jschaul** [comment]
> > The other option could be to write the swagger json(s) to a file when compiling, and move it into a file e.g. brig can read from disk in its container. Then no new http calls need to be made.
> 
> If we move the API types to `wire-api`, brig can just have the swagger, we won't have to do any changes to our build system

Good point!

**Comment by akshaymankar** [comment]
Superseded by #1508

**Pull request closed without merging**
