### PR TITLE
Release 2020-07-29

### PR DESCRIPTION
**Pull request by fisx**
## Release Notes

* This release makes a couple of changes to the elasticsearch mapping and requires a data migration. The correct order of upgrade is:
  1. [Update mapping](./docs/reference/elastic-search.md#update-mapping)
  1. Upgrade brig as usual
  1. [Run data migration](./docs/reference/elastic-search.md#migrate-data)
  Search should continue to work normally during this upgrade.
* Now with cargohold using V4 signatures, the region is part of the Authorization header, so please make sure it is configured correctly. This can be provided the same way as the AWS credentials, e.g. using the AWS_REGION environment variable.

## Bug Fixes

* Fix member count of suspended teams in journal events (#1171)
* Disallow team creation when setRestrictUserCreation is true (#1174)

## New Features

* Pending invitations by email lookup (#1168)
* Support s3 v4 signatures (and use package amazonka instead of aws in cargohold) (#1157)
* Federation: Implement ID mapping (brig) (#1162)

## Internal changes

* SCIM cleanup; drop table `spar.scim_user` (#1169, #1172)
* ormolu script: use ++FAILURES as it will not evaluate to 0 (#1178)
* Refactor: Simplify SRV lookup logic in federation-util (#1175)
* handy cqlsh make target to manually poke at the database (#1170)
* hscim: add license headers (#1165)
* Upgrade stack to 2.3.1 (#1166)
* gundeck: drop deprecated tables (#1163)

### CODE REVIEW

**Comment by mheinzel** [comment]
Could we add a note to the release notes along the lines of

> Now with cargohold using V4 signatures, the region is part of the Authorization header, so please make sure it is configured correctly. This can be provided the same way as the AWS credentials, e.g. using the `AWS_REGION` environment variable.

We already took care of this in `wire-server-deploy` (https://github.com/wireapp/wire-server-deploy/pull/314), but it might still be useful to list here?

**Comment by fisx** [comment]
> Could we add a note to the release notes along the lines of
> 
> > Now with cargohold using V4 signatures, the region is part of the Authorization header, so please make sure it is configured correctly. This can be provided the same way as the AWS credentials, e.g. using the `AWS_REGION` environment variable.
> 
> We already took care of this in `wire-server-deploy` ([wireapp/wire-server-deploy#314](https://github.com/wireapp/wire-server-deploy/pull/314)), but it might still be useful to list here?

done: c9f68342cc53080ec1c2ebfac80c200dc06c371d

**Comment by akshaymankar** [comment]
> done: [c9f6834](https://github.com/wireapp/wire-server/commit/c9f68342cc53080ec1c2ebfac80c200dc06c371d)

It is on wrong branch! :smile:

**Comment by fisx** [comment]
oops

b30d08a2d93f0c520fff7e85008cc688043fcdb8

**Pull request merged**
