### PR TITLE
Fix content-type headers in saml responses.

### PR DESCRIPTION
**Pull request by fisx**

### CODE REVIEW

**Comment by fisx** [comment]
I wrote a `ServerError` body to a file using `Data.ByteString.Lazy.writeFile` and confirmed that it is UTF-8 encoded:

```
$ file /tmp/x
/tmp/x: XML 1.0 document, UTF-8 Unicode text, with very long lines, with no line terminators
```

Interesting: when I insert a `Ümläüts` into a `LByteString` [here](https://github.com/wireapp/wire-server/blob/3af1aa63a9cb4d6594a4e017b0ba38408c0f26d2/services/spar/src/Spar/App.hs#L465), the encoding changes to ISO-8859; if I type the string literal as `Text` and `cs` it, it's back to `UTF-8`.  This may be another reason why we want to close https://github.com/zinfra/backend-issues/issues/1476...

**Comment by smatting** [comment]
From https://hackage.haskell.org/package/bytestring-0.11.0.0/docs/Data-ByteString.html
Beware: fromString truncates multi-byte characters
So you must no have any string literals with non-ascii characters.

**Comment by fisx** [comment]
> Let's use `Text` and be safe.

i don't think that's an option.  it's hard-coded in servant :(

**Comment by smatting** [comment]
Yes, but you can encode only at the last step (see my commit)

**Comment by fisx** [comment]
Sorry, i wasn't reading very carefully.  Got it, thanks for the fix!

I added another nit-pick commit, but I think this should get merged.  @smatting please see if you want to approve, and if so, feel free to merge (squash-rebase, probably) right away.

Spar tests pass locally.

**Review by smatting — APPROVED** [review]

**Pull request merged**
