### PR TITLE
SQCORE-1166: Port Brig SearchAPI and UserRichInfo endpoints to Servant (CI copy)

### PR DESCRIPTION
**Pull request by mdimjasevic**
(This is a copy of @isovector 's PR #2577 so it runs in the CI.)

This PR finishes the work on SQCORE-1166, porting miscellaneous brig endpoints to servant.

## Checklist

 - [x] The **PR Title** explains the impact of the change.
 - [x] The **PR description** provides context as to why the change should occur and what the code contributes to that effect. This could also be a link to a JIRA ticket or a Github issue, if there is one.
 - [x] **changelog.d** contains the following bits of information ([details](https://github.com/wireapp/wire-server/blob/develop/docs/developer/changelog.md)):
   - [x] A file with the changelog entry in one or more suitable sub-sections. The sub-sections are marked by directories inside `changelog.d`.

### CODE REVIEW

**Review by mdimjasevic — COMMENTED** [review]
@isovector , I created a copy PR of your PR for CI reasons.

You can see a few minor fixes I did w.r.t. compilation and documentation. Now I approve the PR, but GitHub wouldn't let me approve it via its interface because I opened this PR. Do you want to approve it?

**Comment by mdimjasevic** [comment]
@isovector , for a future reference, as of yesterday it should be possible (thanks to Akshay) to run CI on a PR coming from your fork of `wire-server` (but I suppose I won't be able to push to your fork if there will be anything to touch up).

**Comment by mdimjasevic** [comment]
@isovector , you inadvertently changed the behavior of the get-rich-info endpoint. I don't understand how the endpoint should behave, but an integration test was failing:

```
    rich info
      there is default empty rich info:                                                FAIL (0.53s)
        test/integration/API/User/RichInfo.hs:64:
        rich info is not empty, or not present
        expected: Right (RichInfoAssocList {unRichInfoAssocList = []})
         but got: Left 404
        Use -p '(!/turn/&&!/user.auth.cookies.limit/)&&/there is default empty rich info/' to rerun this test only.
```

In a commit 771106e30847278691cba8f35a8d0a6a48943d51 I addressed that.

**Comment by isovector** [comment]
Thanks for tackling that, @mdimjasevic !

**Review by elland — APPROVED** [review]
🚀

**Pull request merged**
