### PR TITLE
Federation: Add getUserClients RPC to brig

### PR DESCRIPTION
**Pull request by smatting**
This PR
- adds the `getUserClients` RPC to brig's federation API.
- implements the stubs in 3 public endpoints that retrieve `PubClient` values for remote users

### CODE REVIEW

**Review by jschaul — COMMENTED** [review]
Question: Do you intend to hook this call into the existing client-server API of `/users/{domain}/{uid}/clients` in this or an upcoming PR?

Which information exactly do clients need about other user's clients? The `PubClient` type and the `toPubClient` function are in use for current client-server APIs returning clients. The `UserClients` type seems to so far only be used for internal endpoints and tests (or did I see this wrong? I only did a brief grepping). For message sending and the backend in galley, perhaps we only need the IDs. But other user's clients probably want to also know their device class for displaying in the UI perhaps. Perhaps giving back a map of UserId to PubClient might make sense here?

**Comment by smatting** [comment]
> Question: Do you intend to hook this call into the existing client-server API of `/users/{domain}/{uid}/clients` in this or an upcoming PR?
I hooked it into the the client endpoints. However end2end tests are not included. Should we add them?

> Which information exactly do clients need about other user's clients? ...
I changed the response type to `PubClient`.

**Review by jschaul — APPROVED** [review]
Adding one end2end test for this endpoint (`/users/{domain}/{uid}/clients`) might be nice, otherwise this PR looks good I think.

**Comment by pcapriotti** [comment]
Thanks, I was indeed writing an End2End test.

**Review by jschaul — APPROVED** [review]

**Pull request merged**
