### PR TITLE
Hook fedcalls into api docs

### PR DESCRIPTION
**Pull request by fisx**
Follow-up to https://github.com/wireapp/wire-server/pull/2973. Title says it all.

2023-01-16-103727_1920x1080_scrot

## Checklist

 - [x] Add a new entry in an appropriate subdirectory of `changelog.d`
 - [x] Read and follow the [PR guidelines](https://docs.wire.com/developer/developer/pr-guidelines.html)

### CODE REVIEW

**Comment by fisx** [comment]
@arthurwolf I'm pretty confident I have violated the spirit of the structure of wire-docs.  Could you show me what needs to be changed?

**Comment by arthurwolf** [comment]
> I'm pretty confident I have violated the spirit of the structure of wire-docs. Could you show me what needs to be changed?

Yes, you want anything federation-related to go into the federation/ side of documentation.

If you move the new content there, it should then be fine, ping me and i'll review then (or tell me if you want me to do the move, and i'll try to)

**Comment by fisx** [comment]
> Yes, you want anything federation-related to go into the federation/ side of documentation.

done!  could you take another look?

**Review by arthurwolf — APPROVED** [review]
looks good to me

**Pull request merged**
