### PR TITLE
charts: Mark all test resources to be only created while running tests

### PR DESCRIPTION
**Pull request by akshaymankar**
## Checklist

 - [x] Add a new entry in an appropriate subdirectory of `changelog.d`
 - [x] Read and follow the [PR guidelines](https://docs.wire.com/developer/developer/pr-guidelines.html)

### CODE REVIEW

**Review by jschaul — APPROVED** [review]
As long as CI is happy, this looks good.

I'm not sure configmaps need this annotation, but it probably also doesn't hurt.

**Comment by akshaymankar** [comment]
> I'm not sure configmaps need this annotation, but it probably also doesn't hurt.

I thought why create these resources at all in the non-testing scenarios.

**Review by smatting — APPROVED** [review]

**Comment by akshaymankar** [comment]
`helm test --logs` assumes that every test resource is a pod :facepalm:

**Comment by jschaul** [comment]
> `helm test --logs` assumes that every test resource is a pod facepalm [helm/helm#11236](https://github.com/helm/helm/issues/11236)

I'm reworking how helm test works in https://github.com/wireapp/wire-server/pull/3040

then this issue goes away. So review and merge that PR first, then this one might go green?

**Comment by akshaymankar** [comment]
Ah thanks! I was very confused to see the test fail in exactly the same way. I will change the pipeline I guess.

**Comment by jschaul** [comment]
> Ah thanks! I was very confused to see the test fail in exactly the same way. I will change the pipeline I guess.

Or bump the version of helm in use inside cailleach with the same patch, that would also work I suppose.

**Comment by akshaymankar** [comment]
> 

I vaguely remember wanting to get rid of cailleach-image as much as possible for running integration tests and since we don't rely on any sops machinery anymore we shouldn't need it. I have changed the pipeline already. Hopefully things go green now :crossed_fingers:

**Review by smatting — APPROVED** [review]

**Pull request merged**
