### PR TITLE
Make file sharing feature configurable at instance level.

### PR DESCRIPTION
**Pull request by fisx**
https://wearezeta.atlassian.net/browse/SQSERVICES-622

Related: https://github.com/wireapp/wire-server/pull/1652

## Checklist

 - [x] Title of this PR explains the impact of the change.
 - [x] The description provides context as to why the change should occur and what the code contributes to that effect. This could also be a link to a JIRA ticket or a Github issue, if there is one.
 - [x] The CHANGELOG.md file in the *Unreleased* section has been updated to explain the change which will be included in the release notes.
 - [x] If a component uses a new or changed internal endpoint of another component, this is mentioned in the CHANGELOG.md.
- [x] If this PR creates a new endpoint, or adds a new configuration flag, the endpoint / config-flag checklist (see Wire-employee only backend [wiki page](https://github.com/zinfra/backend-wiki/wiki/Checklists)) has been followed.

### CODE REVIEW

**Comment by fisx** [comment]
If I change this:

```
     fileSharing:
       defaults:
-        status: enabled
+        status: disabled
```

I get this:

```
      FileSharing:                                                                                                                            FAIL
        Exception: Assertions failed:
         2: Right TeamFeatureDisabled =/= Right TeamFeatureEnabled

        Response was:

        Response {responseStatus = Status {statusCode = 200, statusMessage = "OK"}, responseVersion = HTTP/1.1, responseHeaders = [("Transfer-Encoding","chunked"),("Date","Mon, 12 Jul 2021 19:04:15 GMT"),("Server","Warp/3.3.13"),("Content-Encoding","gzip"),("Content-Type","application/json;charset=utf-8")], responseBody = Just "{\"status\":\"disabled\"}", responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}
        CallStack (from HasCallStack):
          error, called at src/Bilge/Assert.hs:89:5 in bilge-0.22.0-KwPXBVYHFlF3OFbmYHfwv3:Bilge.Assert
          <!!, called at src/Bilge/Assert.hs:107:19 in bilge-0.22.0-KwPXBVYHFlF3OFbmYHfwv3:Bilge.Assert
          !!!, called at test/integration/API/Teams/Feature.hs:251:3 in main:API.Teams.Feature
          assertFlagNoConfig, called at test/integration/API/Teams/Feature.hs:208:15 in main:API.Teams.Feature
          getFlag, called at test/integration/API/Teams/Feature.hs:225:3 in main:API.Teams.Feature
          testSimpleFlag, called at test/integration/API/Teams/Feature.hs:46:30 in main:API.Teams.Feature
```

Not sure it's worth adding this as a test case?  As things are now, this requires a lot of boilerplate and runtime.

**Comment by smatting** [comment]
> Not sure it's worth adding this as a test case? As things are now, this requires a lot of boilerplate and runtime.

I don't think it's necessary. I left a comment in the test though: https://github.com/wireapp/wire-server/pull/1654/commits/406b2fff233cd0efaad9c807b85ddd5801170fd1

**Review by smatting — APPROVED** [review]
I trust the manual test is good enough.

**Comment by jschaul** [comment]
Maybe this PR could wait for #1626 to have landed? That includes some test helpers as well for feature flags. #1626 is ready to merge except that tests on develop are broken currently so CI doesn't pass.

**Comment by fisx** [comment]
> Maybe this PR could wait for #1626 to have landed? That includes some test helpers as well for feature flags. #1626 is ready to merge except that tests on develop are broken currently so CI doesn't pass.

Good idea given enough time, but I am leaning towards @smatting and "integration test would be nice, but the manual test is good enough".

**Pull request merged**
