### PR TITLE
Fail on focussed

### PR DESCRIPTION
**Pull request by fisx**
https://github.com/wireapp/wire-server/pull/1488#issuecomment-832654944

### CODE REVIEW

**Comment by fisx** [comment]
The directory I've picked is just a shot in the dark.  Needs to be `~` or `.` when the CI pipeline is alive.

**Comment by fisx** [comment]
(Locally I confirmed that stack runs test with package root as wd, so we *could* just add a million hspecs all over the place.)

**Comment by fisx** [comment]
> (Locally I confirmed that stack runs test with package root as wd, so we _could_ just add a million `.hspec` files all over the place.)

**Comment by fisx** [comment]
...  or something like `echo --fail-on-focused >> ~/.hspec` somewhere where the CI pipeline will pick it up?  (where would that be?)

**Comment by akshaymankar** [comment]
I implemeted this in #1491, maybe this can be closed?

**Comment by fisx** [comment]
solved here: https://github.com/wireapp/wire-server/pull/1491

**Pull request closed without merging**
