### PR TITLE
Bump ghc to 8.4.4.

### PR DESCRIPTION
**Pull request by fisx**
Lots of bugs in ghc-8.4.3...

This change requires re-building over 400 packages.

### CODE REVIEW

**Comment by fisx** [comment]
hum, that's annoying:

```
No setup information found for ghc-8.4.4 on your platform.

This probably means a GHC bindist has not yet been added for OS key 'linux64-ncurses6'.

Supported versions: ghc-7.10.3, ghc-8.0.1, ghc-8.0.2, ghc-8.2.1, ghc-8.2.2
```

also, why?  i thought we were on 8.4.3 before, but that's not supported either?

**Comment by jschaul** [comment]
This will not work as-is.

We have an alpine restriction: 

* alpine 3.8, 3.9, 3.10 [uses ghc-8.4.3](https://pkgs.alpinelinux.org/packages?name=ghc&branch=v3.8)
* alpine 3.11 [uses ghc-8.6.5-r3](https://pkgs.alpinelinux.org/packages?name=ghc&branch=v3.11)

Since ghc on alpine links to musl, not libc, one needs to compile ghc at the specific version for the specific version of alpine for that to work. Stack isn't able to download a ghc version for alpine on the fly, so this PR will not work on the current docker images.

I see two options:

1) compile ghc in version 8.4.4 ourselves in the alpine-prebuilder.
2) redo all our docker images and use something else than alpine as a base container.

**Comment by jschaul** [comment]
Note this line: https://github.com/wireapp/wire-server/blob/develop/build/alpine/Dockerfile.prebuilder#L45

We use the ghc provided by alpine, as manually overriding that doesn't work on alpine (see previous comment)

**Comment by arianvp** [comment]
> redo all our docker images and use something else than alpine as a base container.
We have an existing issue discussing this no? Or was this an offline discussion I had with you before?

Anyhow; doing that now seems like a bit of a burden though I do agree with the idea. I think moving to a libc based distro will lead to less surprises personally.  I'd not be against moving to an `ubuntu` base-image.


But to move this PR forward without having to re-engineer our entire CI pipeline how about this:

Create a `stack-alpine.yaml` that sets `compiler: ghc-843`
And keep `stack.yaml` to `compiler: ghc-844`

then use `stack-alpine.yaml` in CI.

Maybe this is too much of a hack. I find it kinda dirty so please hit me with a trout if you disagree

**Comment by jschaul** [comment]
> > redo all our docker images and use something else than alpine as a base container.
> > We have an existing issue discussing this no? Or was this an offline discussion I had with you before?
> 
> Anyhow; doing that now seems like a bit of a burden though I do agree with the idea. I think moving to a libc based distro will lead to less surprises personally. I'd not be against moving to an `ubuntu` base-image.
> 
> But to move this PR forward without having to re-engineer our entire CI pipeline how about this:
> 
> Create a `stack-alpine.yaml` that sets `compiler: ghc-843`
> And keep `stack.yaml` to `compiler: ghc-844`
> 
> then use `stack-alpine.yaml` in CI.
> 
> Maybe this is too much of a hack. I find it kinda dirty so please hit me with a trout if you disagree

Hmm. We've compiled ghc before as linked in my previous comment, and e.g. [this project](https://github.com/jkachmar/alpine-haskell-stack) has docker and makefiles that look good for that purpose, so it sounds to me like getting a ghc-8.4.4 into the base image that CI then uses isn't too much effort.

**Comment by fisx** [comment]
> > But to move this PR forward without having to re-engineer our entire CI pipeline how about this:
> > Create a `stack-alpine.yaml` that sets `compiler: ghc-843`
> > And keep `stack.yaml` to `compiler: ghc-844`
> > then use `stack-alpine.yaml` in CI.
> > Maybe this is too much of a hack. I find it kinda dirty so please hit me with a trout if you disagree

this means that we'd still be running the buggy 843 in prod, right?  i'm against it!  :)

> Hmm. We've compiled ghc before as linked in my previous comment, and e.g. [this project](https://github.com/jkachmar/alpine-haskell-stack) has docker and makefiles that look good for that purpose, so it sounds to me like getting a ghc-8.4.4 into the base image that CI then uses isn't too much effort.

agreed.  i'll give this a try.

**Comment by arianvp** [comment]
There is also https://gitlab.haskell.org/haskell/ghcup which seems to have alpine support for GHC 8.4.4

However though  it seems to do no signature or shasum checking whatsoever; which is slightly worrying to me :/

**Comment by fisx** [comment]
this is complicated!  work continues on branch `akshaymankar/upgrade-ghc-again`...

TODO:

- [ ] fix [concourse pipeline](https://bridge-ie-concourse.zinfra.io/teams/main/pipelines/tools_dev) used for old infrastructure that builds a deb package.
- [ ] build cryptobox-c docker image in its own pipeline based on its own repo.  use that docker images in wire-server rather than building it here.
- [ ] pin version of cryptobox-c version that is used in Dockerfile.deps and Dockerfile.prebuilder *in one place*.

**Comment by fisx** [comment]
deprecated by #958

**Comment by Z3roCoder** [comment]
Hello,

I am trying to compile the server now and am getting the following error during my "make docker-builder":
"No setup information found for ghc-8.6.5 on your platform.", using Ubuntu 18.04.

Any way around this error?

**Comment by arianvp** [comment]
This branch is old.  develop branch should have the latest stack snapshot and should build

**Comment by Z3roCoder** [comment]
@arianvp I have used the Develop-Branch for this, But I didn't want to start a new Issue for it, thinking maybe it's a quick fix on my side. The exact error message is:

```
stack install --pedantic --test --bench --no-run-benchmarks --local-bin-path=dist
Warnings when parsing snapshot lts-14.12
Unrecognized field in Snapshot: publish-time
No setup information found for ghc-8.6.5 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'linux64-ncurses6'.
Supported versions: ghc-7.10.3, ghc-8.0.1, ghc-8.0.2, ghc-8.2.1, ghc-8.2.2
make: *** [Makefile:14: install] Error 1
The command '/bin/sh -c make clean install' returned a non-zero code: 2
Makefile:128: recipe for target 'docker-intermediate' failed
make: *** [docker-intermediate] Error 2
```

**Comment by arianvp** [comment]
Could you run the following make commands first:

```
make docker-prebuilder
make docker-deps
make docker-builder
make docker-intermediate
```

I think you might have an old cached version of the prebuilder image, and hence docker-intermediate is running with an old version of stack / alpine

**Comment by Z3roCoder** [comment]
@arianvp 

Many thanks! I will try it out soon - Atm I just installed the Haskell Stack and just tried "make" for now.

**Comment by arianvp** [comment]
I'm getting the same error when running _just_ `make docker-intermediate`. In this case I would expect it to fetch the dependencies from `quay` with sufficently new versions. not sure why it is failing. Fully log:

```
[nix-shell:~/Projects/wire/wire-server]$ make docker-intermediate 
# `docker-intermediate` needs to be built whenever code changes - this essentially runs `stack clean && stack install` on the whole repo
docker build -t quay.io/wire/alpine-intermediate:local -f build/alpine/Dockerfile.intermediate --build-arg builder=quay.io/wire/alpine-builder --build-arg deps=quay.io/wire/alpine-deps .;
Sending build context to Docker daemon  47.78MB
Step 1/9 : ARG builder=quay.io/wire/alpine-builder
Step 2/9 : ARG deps=quay.io/wire/alpine-deps
Step 3/9 : FROM ${builder} as builder
 ---> fcaaac9e20fc
Step 4/9 : WORKDIR /wire-server/
 ---> Using cache
 ---> 82d67560b241
Step 5/9 : COPY . /wire-server/
 ---> Using cache
 ---> f15875120688
Step 6/9 : RUN make clean install
 ---> Running in de24187bd048
bash: docker: command not found
stack clean
Warnings when parsing snapshot lts-14.12
Unrecognized field in Snapshot: publish-time
Cloning 0a5142cd3ba48116ff059c041348b817fb7bdb25 from https://github.com/wireapp/hspec-wai
Cloning cc47da1d097b0b26595b8889e40c33c6c0c1c551 from https://github.com/wireapp/hsaml2
Cloning a160cef95d9daaff7d9cfe616d95754c2f8202bf from https://github.com/wireapp/http-client
Cloning a160cef95d9daaff7d9cfe616d95754c2f8202bf from https://github.com/wireapp/http-client
Cloning a160cef95d9daaff7d9cfe616d95754c2f8202bf from https://github.com/wireapp/http-client
Cloning a160cef95d9daaff7d9cfe616d95754c2f8202bf from https://github.com/wireapp/http-client
Cloning 54cc6b14a1bcc27aec630ccdaaf45a4ed9efe0be from https://github.com/wireapp/saml2-web-sso
Cloning 20e2ce169d2c85a10c09b4dc564eacedf8acad68 from https://github.com/wireapp/hscim
make -C services/nginz clean
make[1]: Entering directory '/wire-server/services/nginz'
rm -rf src build .metadata zwagger-ui/swagger-ui
make[1]: Leaving directory '/wire-server/services/nginz'
rm -rf dist
rm -f .metadata
mkdir -p dist
stack install --pedantic --test --bench --no-run-benchmarks --local-bin-path=dist
Warnings when parsing snapshot lts-14.12
Unrecognized field in Snapshot: publish-time
No setup information found for ghc-8.6.5 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'linux64-ncurses6'.
Supported versions: ghc-7.10.3, ghc-8.0.1, ghc-8.0.2, ghc-8.2.1, ghc-8.2.2
make: *** [Makefile:14: install] Error 1
The command '/bin/sh -c make clean install' returned a non-zero code: 2
make: *** [Makefile:129: docker-intermediate] Error 2

```

**Comment by arianvp** [comment]
Ah it seems we do not publish `alpine-builder:latest` anymore, only `alpine-builder:develop` and `alpine-builder:master`. We should update the makefile. Thanks for the report  @Z3roCoder  this seems like an oversight on our side

**Comment by Z3roCoder** [comment]
@arianvp Oh, okay alright! Should I edit the Makefile on my end to fix this, or should I just wait for a fix pushed?

**Comment by arianvp** [comment]
It should be a relatively small change. If you want to do it, feel free to send a PR! otherwise we'll probably pick this up on one of our cleanup fridays

**Comment by Z3roCoder** [comment]
Alright - I'll try to edit the Build/Alpine/Makefile and build and run it on my end and if successful, I'll try to send a PR - So far, it looks promising! Thanks for the quick responses!

**Comment by Z3roCoder** [comment]
@arianvp I am also having Problems with the docker-intermediate command - It doesn't find ghc-8.6.5 either

**Comment by Z3roCoder** [comment]
Latest seems to have been built 2 days ago, but it wouldn't "make" the image;
(https://quay.io/repository/wire/alpine-intermediate?tab=tags)

```
Step 6/9 : RUN make clean install
 ---> Running in f47dd254370b
bash: docker: command not found
stack clean
Warnings when parsing snapshot lts-14.12
Unrecognized field in Snapshot: publish-time
Cloning 0a5142cd3ba48116ff059c041348b817fb7bdb25 from https://github.com/wireapp/hspec-wai
Cloning cc47da1d097b0b26595b8889e40c33c6c0c1c551 from https://github.com/wireapp/hsaml2
Cloning a160cef95d9daaff7d9cfe616d95754c2f8202bf from https://github.com/wireapp/http-client
Cloning a160cef95d9daaff7d9cfe616d95754c2f8202bf from https://github.com/wireapp/http-client
Cloning a160cef95d9daaff7d9cfe616d95754c2f8202bf from https://github.com/wireapp/http-client
Cloning a160cef95d9daaff7d9cfe616d95754c2f8202bf from https://github.com/wireapp/http-client
Cloning 1a1b313092beb685a9bb15685c83a3162c1e220f from https://github.com/wireapp/saml2-web-sso
Cloning 20e2ce169d2c85a10c09b4dc564eacedf8acad68 from https://github.com/wireapp/hscim
make -C services/nginz clean
make[1]: Entering directory '/wire-server/services/nginz'
rm -rf src build .metadata zwagger-ui/swagger-ui
make[1]: Leaving directory '/wire-server/services/nginz'
rm -rf dist
rm -f .metadata
mkdir -p dist
stack install --pedantic --test --bench --no-run-benchmarks --local-bin-path=dist
Warnings when parsing snapshot lts-14.12
Unrecognized field in Snapshot: publish-time
No setup information found for ghc-8.6.5 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'linux64-ncurses6'.
Supported versions: ghc-7.10.3, ghc-8.0.1, ghc-8.0.2, ghc-8.2.1, ghc-8.2.2
make: *** [Makefile:14: install] Error 1
The command '/bin/sh -c make clean install' returned a non-zero code: 2
Makefile:128: recipe for target 'docker-intermediate' failed
make: *** [docker-intermediate] Error 2
```

**Pull request closed without merging**
