### PR TITLE
Change of team permission semantics

### PR DESCRIPTION
**Pull request by fisx**

### CODE REVIEW

**Comment by fisx** [comment]
@tiago-loureiro what did I miss?  I am planning to write one integration test for `updateConversation` that fails for an external member, would you like to see any other tests?

**Comment by fisx** [comment]
CI doesn't give me the log of the failed test run.  Integration tests pass locally for me.

**Comment by jschaul** [comment]
>  CI doesn't give me the log of the failed test run.

here it is:

(galley)
```
  add new team member internal:                                FAIL (0.22s)
      test/integration/API/Teams.hs:250:
      billing users
      expected: ["\STX\167\235B%N@r\135\&4\240~\SOH\STX\"#"]
       but got: ["\253\\\136\USA@LG\128\176\&7\204\181}0;","\STX\167\235B%N@r\135\&4\240~\SOH\STX\"#"]
```

**Comment by fisx** [comment]
thanks!  this happens locally:

```
    add new team member internal:                                OK (0.13s)
```

i guess i need to run the real aws tests...

**Comment by fisx** [comment]
I am somewhat hopeful that I have made the test pass, but I'm not sure it's still consistent with the intended meaning?

**Comment by fisx** [comment]
Possible further test cases:

- `testUpdateTeamConv`, but with creating a non-team conversation
- corresponding tests for `updateConversationAccess`, `updateConversationReceiptMode`, `updateConversationMessageTimer`.

Should I...?  (Preferably in a separate PR.)

**Comment by fisx** [comment]
```
    update conversation as member:                               FAIL (0.17s)
      test/integration/API/Teams.hs:507:
      status
      expected: 200
       but got: 403
```

**Comment by fisx** [comment]
I may have forgotten these:
- `Open/close to guests`?  (where do i find that?)
- `Create/remove link`?  (is this `POST /conversations/{cnv}/code`?)

**Comment by jschaul** [comment]
> Open/close to guests? (where do i find that?)

See https://github.com/wireapp/wire-server/blob/e9ea65f69d5c4559046b7902041ff152824fc0a5/libs/galley-types/src/Galley/Types.hs#L115-L133 - it's part of the conversation metadata.

> Create/remove link? (is this POST /conversations/{cnv}/code?)

yes. But being able to add/remove conversation codes are tied to the access mode of the conversation itself though, not to the person doing the request.

**Pull request merged**
