### PR TITLE
Cleanup stack.yaml.

### PR DESCRIPTION
**Pull request by fisx**
these have been released on hackage two months ago.

### CODE REVIEW

**Comment by fisx** [comment]
I stumbled over that when trying to get ghc-8.10 for `-Wunused-packages`.  (No luck there, but at least a bit of cleanup.)

**Comment by jschaul** [comment]
```
Failures:


  test-integration/Test/Spar/Scim/UserSpec.hs:640:22: 

  1) Spar.Scim.User, POST /Users, team has no SAML IdP, doesn't list users that exceed their invitation period, and allows recreating them

       uncaught exception: ErrorCall

       Assertions failed:

        1: 400 =/= 409

       

       Response was:

       

       Response {responseStatus = Status {statusCode = 409, statusMessage = "Conflict"}, responseVersion = HTTP/1.1, responseHeaders = [("Transfer-Encoding","chunked"),("Date","Thu, 31 Dec 2020 21:52:24 GMT"),("Server","Warp/3.3.13"),("Content-Encoding","gzip"),("Content-Type","application/json")], responseBody = Just "{\"code\":409,\"message\":\"The given e-mail address or phone number is in use.\",\"label\":\"key-exists\"}", responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}

       CallStack (from HasCallStack):

         error, called at src/Bilge/Assert.hs:88:5 in bilge-0.22.0-LWSwcj5o3J5utdi7oQriS:Bilge.Assert

         <!!, called at test-integration/Util/Invitation.hs:76:7 in main:Util.Invitation

         registerInvitation, called at test-integration/Test/Spar/Scim/UserSpec.hs:640:22 in main:Test.Spar.Scim.UserSpec


  To rerun use: --match "/Spar.Scim.User/POST /Users/team has no SAML IdP/doesn't list users that exceed their invitation period, and allows recreating them/"
```

**Comment by fisx** [comment]
The error looks very unrelated.  @jschaul wanna re-review?

**Review by jschaul — APPROVED** [review]
All green now. Maybe that is a flaky test though? If that flakes again we'd need to deal with it.

**Pull request merged**
