### PR TITLE
Subtree hscim

### PR DESCRIPTION
**Pull request by arianvp**

### CODE REVIEW

**Comment by fisx** [comment]
Jon used to work here, and I'm pretty sure he has signed away his IPR.  Hi @elverkilde o/ :)!

We can either change the author on the resp. commits to `Jon Elverkilde <jon.elverkilde@pusher.com>` and ask him to sign off on it again, redundantly, or just ignore the false warning, merge it as is, and keep the hscim repo around as evidence.

**Comment by akshaymankar** [comment]
Please archive the hscim before (or just after) this gets merged with a note about where to find the latest hscim.

**Comment by fisx** [comment]
can't make a lot of sense out of this, so let's try one more time:

```
bash: docker: command not found
stack clean
<<<<<<<<<<<<<<<<<<
You are currently using Stack version 2.1.3, but version 2.3.1 is available
You can try to upgrade by running 'stack upgrade'
Tired of seeing this? Add 'recommend-stack-upgrade: false' to /root/.stack/config.yaml
>>>>>>>>>>>>>>>>>>

Aeson exception:
Error in $.packages[1].completed: failed to parse field 'packages': failed to parse field 'completed': Could not parse a UnresolvedPackageLocationImmutable from: Object (fromList [("subdir",String "wai-middleware-prometheus"),("name",String "wai-middleware-prometheus"),("version",String "1.0.0"),("git",String "https://github.com/fimad/prometheus-haskell"),("pantry-tree",Object (fromList [("size",Number 359.0),("sha256",String "72560f0d8c7f57db769e77d491e8b10255938631847981de52e94781b905a27a")])),("commit",String "2e3282e5fb27ba8d989c271a0a989823fad7ec43")])
make: *** [Makefile:64: clean] Error 1
The command '/bin/sh -c make clean install' returned a non-zero code: 2
```

or perhaps there is something about `git-subtree` that we need to sort out on ci?

**Comment by fisx** [comment]
same error.  I've removed libs/hscim from stack.yaml, let's see if that changes anything.  but there is no mention of `docker` in libs/hscim, so this looks to me like some unrelated concourse issue.

**Comment by arianvp** [comment]
You somehow commited a corrupted `lockfile`  (Removed all kinds of cabal hashes) which seems very off.  Please make sure that you're running the same version of stack and hpack as CI.  Stack  is not stable across versions and will break in inexplicable ways

**Comment by arianvp** [comment]
`hscim` unit test build seems to fail; but the logs stack outputs are all over the place and hard to read so I cant figure out what is failing

**Comment by arianvp** [comment]
@fisx it seems the `hscim`  `doctests` are failing. I have no experience with doctests.  It might be that they were broken all along because I never ran them.  There don't seem to be logs _what_ failed in the doctests.     Can we get rid of them? they seem akward.

**Pull request merged**
